# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home.ui',
# licensing of 'home.ui' applies.
#
# Created: Sun Dec  9 17:49:44 2018
#      by: pyside2-uic  running on PySide2 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Home(object):
    def setupUi(self, Home):
        Home.setObjectName("Home")
        Home.resize(635, 396)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("IMG/logoblack.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Home.setWindowIcon(icon)
        Home.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(Home)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.leSearch = QtWidgets.QLineEdit(self.centralwidget)
        self.leSearch.setText("")
        self.leSearch.setObjectName("leSearch")
        self.horizontalLayout_3.addWidget(self.leSearch)
        self.lbSearch = QtWidgets.QLabel(self.centralwidget)
        self.lbSearch.setMaximumSize(QtCore.QSize(29, 29))
        self.lbSearch.setText("")
        self.lbSearch.setPixmap(QtGui.QPixmap("../../Imagens/Icones/123368-color-startups-and-new-business/png/magnifying-glass.png"))
        self.lbSearch.setScaledContents(True)
        self.lbSearch.setObjectName("lbSearch")
        self.horizontalLayout_3.addWidget(self.lbSearch)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.cbSearch = QtWidgets.QComboBox(self.centralwidget)
        self.cbSearch.setObjectName("cbSearch")
        self.cbSearch.addItem("")
        self.cbSearch.addItem("")
        self.cbSearch.addItem("")
        self.cbSearch.addItem("")
        self.cbSearch.addItem("")
        self.cbSearch.addItem("")
        self.horizontalLayout_4.addWidget(self.cbSearch)
        spacerItem3 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pbClient = QtWidgets.QPushButton(self.centralwidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("IMG/team.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbClient.setIcon(icon1)
        self.pbClient.setIconSize(QtCore.QSize(32, 32))
        self.pbClient.setObjectName("pbClient")
        self.horizontalLayout_2.addWidget(self.pbClient)
        self.pbSo = QtWidgets.QPushButton(self.centralwidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("IMG/documentation.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbSo.setIcon(icon2)
        self.pbSo.setIconSize(QtCore.QSize(32, 32))
        self.pbSo.setCheckable(False)
        self.pbSo.setObjectName("pbSo")
        self.horizontalLayout_2.addWidget(self.pbSo)
        self.pbStock = QtWidgets.QPushButton(self.centralwidget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("IMG/store.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbStock.setIcon(icon3)
        self.pbStock.setIconSize(QtCore.QSize(32, 32))
        self.pbStock.setObjectName("pbStock")
        self.horizontalLayout_2.addWidget(self.pbStock)
        self.pbFinancial = QtWidgets.QPushButton(self.centralwidget)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("IMG/diagram-1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbFinancial.setIcon(icon4)
        self.pbFinancial.setIconSize(QtCore.QSize(32, 32))
        self.pbFinancial.setObjectName("pbFinancial")
        self.horizontalLayout_2.addWidget(self.pbFinancial)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pbSales = QtWidgets.QPushButton(self.centralwidget)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("IMG/website.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbSales.setIcon(icon5)
        self.pbSales.setIconSize(QtCore.QSize(32, 32))
        self.pbSales.setObjectName("pbSales")
        self.horizontalLayout.addWidget(self.pbSales)
        self.pbTeam = QtWidgets.QPushButton(self.centralwidget)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("IMG/employees.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbTeam.setIcon(icon6)
        self.pbTeam.setIconSize(QtCore.QSize(32, 32))
        self.pbTeam.setObjectName("pbTeam")
        self.horizontalLayout.addWidget(self.pbTeam)
        self.pbProvider = QtWidgets.QPushButton(self.centralwidget)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("IMG/truck-1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbProvider.setIcon(icon7)
        self.pbProvider.setIconSize(QtCore.QSize(32, 32))
        self.pbProvider.setObjectName("pbProvider")
        self.horizontalLayout.addWidget(self.pbProvider)
        self.pbSettings = QtWidgets.QPushButton(self.centralwidget)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("IMG/cogwheel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbSettings.setIcon(icon8)
        self.pbSettings.setIconSize(QtCore.QSize(32, 32))
        self.pbSettings.setObjectName("pbSettings")
        self.horizontalLayout.addWidget(self.pbSettings)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        Home.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Home)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 635, 30))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuNew = QtWidgets.QMenu(self.menuFile)
        self.menuNew.setObjectName("menuNew")
        self.menuPesquisar = QtWidgets.QMenu(self.menuFile)
        self.menuPesquisar.setObjectName("menuPesquisar")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuExit = QtWidgets.QMenu(self.menubar)
        self.menuExit.setObjectName("menuExit")
        Home.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Home)
        self.statusbar.setObjectName("statusbar")
        Home.setStatusBar(self.statusbar)
        self.actionManual = QtWidgets.QAction(Home)
        self.actionManual.setObjectName("actionManual")
        self.actionSupport = QtWidgets.QAction(Home)
        self.actionSupport.setObjectName("actionSupport")
        self.actionAbout = QtWidgets.QAction(Home)
        self.actionAbout.setObjectName("actionAbout")
        self.actionClient = QtWidgets.QAction(Home)
        self.actionClient.setObjectName("actionClient")
        self.actionSo = QtWidgets.QAction(Home)
        self.actionSo.setObjectName("actionSo")
        self.actionProduct = QtWidgets.QAction(Home)
        self.actionProduct.setObjectName("actionProduct")
        self.actionProvider = QtWidgets.QAction(Home)
        self.actionProvider.setObjectName("actionProvider")
        self.actionClient_2 = QtWidgets.QAction(Home)
        self.actionClient_2.setObjectName("actionClient_2")
        self.actionSo_2 = QtWidgets.QAction(Home)
        self.actionSo_2.setObjectName("actionSo_2")
        self.actionProduct_2 = QtWidgets.QAction(Home)
        self.actionProduct_2.setObjectName("actionProduct_2")
        self.actionProvider_2 = QtWidgets.QAction(Home)
        self.actionProvider_2.setObjectName("actionProvider_2")
        self.menuNew.addAction(self.actionClient)
        self.menuNew.addAction(self.actionSo)
        self.menuNew.addAction(self.actionProduct)
        self.menuNew.addAction(self.actionProvider)
        self.menuPesquisar.addAction(self.actionClient_2)
        self.menuPesquisar.addAction(self.actionSo_2)
        self.menuPesquisar.addAction(self.actionProduct_2)
        self.menuPesquisar.addAction(self.actionProvider_2)
        self.menuFile.addAction(self.menuNew.menuAction())
        self.menuFile.addAction(self.menuPesquisar.menuAction())
        self.menuHelp.addAction(self.actionManual)
        self.menuHelp.addAction(self.actionSupport)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menubar.addAction(self.menuExit.menuAction())

        self.retranslateUi(Home)
        QtCore.QMetaObject.connectSlotsByName(Home)

    def retranslateUi(self, Home):
        Home.setWindowTitle(QtWidgets.QApplication.translate("Home", "HL INFORMÁTICA", None, -1))
        self.leSearch.setPlaceholderText(QtWidgets.QApplication.translate("Home", " Pesquisar...", None, -1))
        self.cbSearch.setItemText(0, QtWidgets.QApplication.translate("Home", "Ordem de Serviço", None, -1))
        self.cbSearch.setItemText(1, QtWidgets.QApplication.translate("Home", "Cliente", None, -1))
        self.cbSearch.setItemText(2, QtWidgets.QApplication.translate("Home", "Produto", None, -1))
        self.cbSearch.setItemText(3, QtWidgets.QApplication.translate("Home", "CPF", None, -1))
        self.cbSearch.setItemText(4, QtWidgets.QApplication.translate("Home", "Marca", None, -1))
        self.cbSearch.setItemText(5, QtWidgets.QApplication.translate("Home", "Modelo", None, -1))
        self.pbClient.setText(QtWidgets.QApplication.translate("Home", "Clientes", None, -1))
        self.pbSo.setText(QtWidgets.QApplication.translate("Home", "Ordem de Serviço", None, -1))
        self.pbStock.setText(QtWidgets.QApplication.translate("Home", "Estoque", None, -1))
        self.pbFinancial.setText(QtWidgets.QApplication.translate("Home", "Financeiro", None, -1))
        self.pbSales.setText(QtWidgets.QApplication.translate("Home", "Ponto de Vendas", None, -1))
        self.pbTeam.setText(QtWidgets.QApplication.translate("Home", "Equipe", None, -1))
        self.pbProvider.setText(QtWidgets.QApplication.translate("Home", "Fornecedores", None, -1))
        self.pbSettings.setText(QtWidgets.QApplication.translate("Home", "Ajustes", None, -1))
        self.menuFile.setTitle(QtWidgets.QApplication.translate("Home", "Ar&quivo", None, -1))
        self.menuNew.setTitle(QtWidgets.QApplication.translate("Home", "&Novo", None, -1))
        self.menuPesquisar.setTitle(QtWidgets.QApplication.translate("Home", "&Pesquisar", None, -1))
        self.menuHelp.setTitle(QtWidgets.QApplication.translate("Home", "A&juda", None, -1))
        self.menuExit.setTitle(QtWidgets.QApplication.translate("Home", "Sair", None, -1))
        self.actionManual.setText(QtWidgets.QApplication.translate("Home", "&Manual", None, -1))
        self.actionSupport.setText(QtWidgets.QApplication.translate("Home", "&Suporte", None, -1))
        self.actionAbout.setText(QtWidgets.QApplication.translate("Home", "S&obre", None, -1))
        self.actionClient.setText(QtWidgets.QApplication.translate("Home", "&Cliente", None, -1))
        self.actionSo.setText(QtWidgets.QApplication.translate("Home", "&Ordem Serviço", None, -1))
        self.actionProduct.setText(QtWidgets.QApplication.translate("Home", "&Produto", None, -1))
        self.actionProvider.setText(QtWidgets.QApplication.translate("Home", "&Fornecedor", None, -1))
        self.actionClient_2.setText(QtWidgets.QApplication.translate("Home", "&Cliente", None, -1))
        self.actionSo_2.setText(QtWidgets.QApplication.translate("Home", "&Ordem Serviço", None, -1))
        self.actionProduct_2.setText(QtWidgets.QApplication.translate("Home", "&Produto", None, -1))
        self.actionProvider_2.setText(QtWidgets.QApplication.translate("Home", "&Fornecedor", None, -1))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Home = QtWidgets.QMainWindow()
    ui = Ui_Home()
    ui.setupUi(Home)
    Home.show()
    sys.exit(app.exec_())

