# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sorder.ui',
# licensing of 'sorder.ui' applies.
#
# Created: Sun Apr 21 02:02:32 2019
#      by: pyside2-uic  running on PySide2 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_SOrderEdit(object):
    def setupUi(self, SOrderEdit):
        SOrderEdit.setObjectName("SOrderEdit")
        SOrderEdit.resize(776, 686)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("IMG/logoblack.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SOrderEdit.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(SOrderEdit)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.lbWindow = QtWidgets.QLabel(SOrderEdit)
        self.lbWindow.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.lbWindow.setFont(font)
        self.lbWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbWindow.setAlignment(QtCore.Qt.AlignCenter)
        self.lbWindow.setObjectName("lbWindow")
        self.horizontalLayout_12.addWidget(self.lbWindow)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.lbOs = QtWidgets.QLabel(SOrderEdit)
        self.lbOs.setMaximumSize(QtCore.QSize(30, 16777215))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.lbOs.setFont(font)
        self.lbOs.setStyleSheet("color: rgb(255, 0, 0);")
        self.lbOs.setObjectName("lbOs")
        self.horizontalLayout_23.addWidget(self.lbOs)
        self.leOs = QtWidgets.QLineEdit(SOrderEdit)
        self.leOs.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leOs.sizePolicy().hasHeightForWidth())
        self.leOs.setSizePolicy(sizePolicy)
        self.leOs.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.leOs.setText("")
        self.leOs.setReadOnly(True)
        self.leOs.setObjectName("leOs")
        self.horizontalLayout_23.addWidget(self.leOs)
        self.lbStatus1 = QtWidgets.QLabel(SOrderEdit)
        self.lbStatus1.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.lbStatus1.setFont(font)
        self.lbStatus1.setStyleSheet("color: rgb(255, 0, 0);")
        self.lbStatus1.setObjectName("lbStatus1")
        self.horizontalLayout_23.addWidget(self.lbStatus1)
        self.lbStatus2 = QtWidgets.QLabel(SOrderEdit)
        self.lbStatus2.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lbStatus2.setObjectName("lbStatus2")
        self.horizontalLayout_23.addWidget(self.lbStatus2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.lbEntryDate = QtWidgets.QLabel(SOrderEdit)
        self.lbEntryDate.setObjectName("lbEntryDate")
        self.horizontalLayout_25.addWidget(self.lbEntryDate)
        self.dtEntryDate = QtWidgets.QDateTimeEdit(SOrderEdit)
        self.dtEntryDate.setEnabled(False)
        self.dtEntryDate.setReadOnly(True)
        self.dtEntryDate.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.dtEntryDate.setObjectName("dtEntryDate")
        self.horizontalLayout_25.addWidget(self.dtEntryDate)
        self.label = QtWidgets.QLabel(SOrderEdit)
        self.label.setObjectName("label")
        self.horizontalLayout_25.addWidget(self.label)
        self.dtAltDate = QtWidgets.QDateTimeEdit(SOrderEdit)
        self.dtAltDate.setEnabled(False)
        self.dtAltDate.setReadOnly(True)
        self.dtAltDate.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.dtAltDate.setObjectName("dtAltDate")
        self.horizontalLayout_25.addWidget(self.dtAltDate)
        self.lbOutDate = QtWidgets.QLabel(SOrderEdit)
        self.lbOutDate.setObjectName("lbOutDate")
        self.horizontalLayout_25.addWidget(self.lbOutDate)
        self.dtOutDate = QtWidgets.QDateTimeEdit(SOrderEdit)
        self.dtOutDate.setEnabled(False)
        self.dtOutDate.setFrame(True)
        self.dtOutDate.setReadOnly(True)
        self.dtOutDate.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.dtOutDate.setObjectName("dtOutDate")
        self.horizontalLayout_25.addWidget(self.dtOutDate)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_25)
        self.tabWidget = QtWidgets.QTabWidget(SOrderEdit)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setFocusPolicy(QtCore.Qt.TabFocus)
        self.tabWidget.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setBaseSize(QtCore.QSize(0, 0))
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.lbCodCli = QtWidgets.QLabel(self.groupBox)
        self.lbCodCli.setObjectName("lbCodCli")
        self.horizontalLayout_16.addWidget(self.lbCodCli)
        self.leCodCli = QtWidgets.QLineEdit(self.groupBox)
        self.leCodCli.setMaximumSize(QtCore.QSize(100, 16777215))
        self.leCodCli.setReadOnly(True)
        self.leCodCli.setObjectName("leCodCli")
        self.horizontalLayout_16.addWidget(self.leCodCli)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lbName = QtWidgets.QLabel(self.groupBox)
        self.lbName.setObjectName("lbName")
        self.horizontalLayout_4.addWidget(self.lbName)
        self.leName = QtWidgets.QLineEdit(self.groupBox)
        self.leName.setReadOnly(True)
        self.leName.setObjectName("leName")
        self.horizontalLayout_4.addWidget(self.leName)
        self.pbSearch = QtWidgets.QPushButton(self.groupBox)
        self.pbSearch.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("IMG/magnifying-glass.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbSearch.setIcon(icon1)
        self.pbSearch.setObjectName("pbSearch")
        self.horizontalLayout_4.addWidget(self.pbSearch)
        self.lbBirth = QtWidgets.QLabel(self.groupBox)
        self.lbBirth.setObjectName("lbBirth")
        self.horizontalLayout_4.addWidget(self.lbBirth)
        self.dtBirth = QtWidgets.QDateEdit(self.groupBox)
        self.dtBirth.setReadOnly(True)
        self.dtBirth.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.dtBirth.setObjectName("dtBirth")
        self.horizontalLayout_4.addWidget(self.dtBirth)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbSex = QtWidgets.QLabel(self.groupBox)
        self.lbSex.setObjectName("lbSex")
        self.horizontalLayout.addWidget(self.lbSex)
        self.rbM = QtWidgets.QRadioButton(self.groupBox)
        self.rbM.setCheckable(True)
        self.rbM.setChecked(False)
        self.rbM.setObjectName("rbM")
        self.buttonGroup = QtWidgets.QButtonGroup(SOrderEdit)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.rbM)
        self.horizontalLayout.addWidget(self.rbM)
        self.rbF = QtWidgets.QRadioButton(self.groupBox)
        self.rbF.setObjectName("rbF")
        self.buttonGroup.addButton(self.rbF)
        self.horizontalLayout.addWidget(self.rbF)
        self.lbCpfCnpj = QtWidgets.QLabel(self.groupBox)
        self.lbCpfCnpj.setObjectName("lbCpfCnpj")
        self.horizontalLayout.addWidget(self.lbCpfCnpj)
        self.leCpfCnpj = QtWidgets.QLineEdit(self.groupBox)
        self.leCpfCnpj.setReadOnly(True)
        self.leCpfCnpj.setObjectName("leCpfCnpj")
        self.horizontalLayout.addWidget(self.leCpfCnpj)
        self.lbRgIe = QtWidgets.QLabel(self.groupBox)
        self.lbRgIe.setObjectName("lbRgIe")
        self.horizontalLayout.addWidget(self.lbRgIe)
        self.leRgIe = QtWidgets.QLineEdit(self.groupBox)
        self.leRgIe.setReadOnly(True)
        self.leRgIe.setObjectName("leRgIe")
        self.horizontalLayout.addWidget(self.leRgIe)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_5.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lbCell1 = QtWidgets.QLabel(self.groupBox_2)
        self.lbCell1.setObjectName("lbCell1")
        self.horizontalLayout_2.addWidget(self.lbCell1)
        self.leCell1 = QtWidgets.QLineEdit(self.groupBox_2)
        self.leCell1.setReadOnly(True)
        self.leCell1.setObjectName("leCell1")
        self.horizontalLayout_2.addWidget(self.leCell1)
        self.cbCell1 = QtWidgets.QComboBox(self.groupBox_2)
        self.cbCell1.setMaximumSize(QtCore.QSize(70, 16777215))
        self.cbCell1.setEditable(False)
        self.cbCell1.setObjectName("cbCell1")
        self.cbCell1.addItem("")
        self.cbCell1.setItemText(0, "")
        self.cbCell1.addItem("")
        self.cbCell1.addItem("")
        self.cbCell1.addItem("")
        self.cbCell1.addItem("")
        self.cbCell1.addItem("")
        self.horizontalLayout_2.addWidget(self.cbCell1)
        self.lbCell2 = QtWidgets.QLabel(self.groupBox_2)
        self.lbCell2.setObjectName("lbCell2")
        self.horizontalLayout_2.addWidget(self.lbCell2)
        self.leCell2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.leCell2.setReadOnly(True)
        self.leCell2.setObjectName("leCell2")
        self.horizontalLayout_2.addWidget(self.leCell2)
        self.cbCell2 = QtWidgets.QComboBox(self.groupBox_2)
        self.cbCell2.setMaximumSize(QtCore.QSize(70, 16777215))
        self.cbCell2.setObjectName("cbCell2")
        self.cbCell2.addItem("")
        self.cbCell2.setItemText(0, "")
        self.cbCell2.addItem("")
        self.cbCell2.addItem("")
        self.cbCell2.addItem("")
        self.cbCell2.addItem("")
        self.cbCell2.addItem("")
        self.horizontalLayout_2.addWidget(self.cbCell2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lbTel = QtWidgets.QLabel(self.groupBox_2)
        self.lbTel.setObjectName("lbTel")
        self.horizontalLayout_5.addWidget(self.lbTel)
        self.leTel = QtWidgets.QLineEdit(self.groupBox_2)
        self.leTel.setMaximumSize(QtCore.QSize(120, 16777215))
        self.leTel.setReadOnly(True)
        self.leTel.setObjectName("leTel")
        self.horizontalLayout_5.addWidget(self.leTel)
        self.lbEmail = QtWidgets.QLabel(self.groupBox_2)
        self.lbEmail.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lbEmail.setObjectName("lbEmail")
        self.horizontalLayout_5.addWidget(self.lbEmail)
        self.leEmail = QtWidgets.QLineEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leEmail.sizePolicy().hasHeightForWidth())
        self.leEmail.setSizePolicy(sizePolicy)
        self.leEmail.setMaximumSize(QtCore.QSize(1677215, 16777215))
        self.leEmail.setReadOnly(True)
        self.leEmail.setObjectName("leEmail")
        self.horizontalLayout_5.addWidget(self.leEmail)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.verticalLayout_5.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.lbAdress = QtWidgets.QLabel(self.groupBox_3)
        self.lbAdress.setObjectName("lbAdress")
        self.horizontalLayout_8.addWidget(self.lbAdress)
        self.leAdress = QtWidgets.QLineEdit(self.groupBox_3)
        self.leAdress.setReadOnly(True)
        self.leAdress.setObjectName("leAdress")
        self.horizontalLayout_8.addWidget(self.leAdress)
        self.lbNumber = QtWidgets.QLabel(self.groupBox_3)
        self.lbNumber.setObjectName("lbNumber")
        self.horizontalLayout_8.addWidget(self.lbNumber)
        self.leNumber = QtWidgets.QLineEdit(self.groupBox_3)
        self.leNumber.setMaximumSize(QtCore.QSize(60, 16777215))
        self.leNumber.setReadOnly(True)
        self.leNumber.setObjectName("leNumber")
        self.horizontalLayout_8.addWidget(self.leNumber)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lbAdress2 = QtWidgets.QLabel(self.groupBox_3)
        self.lbAdress2.setObjectName("lbAdress2")
        self.horizontalLayout_6.addWidget(self.lbAdress2)
        self.leAdress2 = QtWidgets.QLineEdit(self.groupBox_3)
        self.leAdress2.setReadOnly(True)
        self.leAdress2.setObjectName("leAdress2")
        self.horizontalLayout_6.addWidget(self.leAdress2)
        self.lbCep = QtWidgets.QLabel(self.groupBox_3)
        self.lbCep.setObjectName("lbCep")
        self.horizontalLayout_6.addWidget(self.lbCep)
        self.leCep = QtWidgets.QLineEdit(self.groupBox_3)
        self.leCep.setMaximumSize(QtCore.QSize(150, 16777215))
        self.leCep.setReadOnly(True)
        self.leCep.setObjectName("leCep")
        self.horizontalLayout_6.addWidget(self.leCep)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lbDistrict = QtWidgets.QLabel(self.groupBox_3)
        self.lbDistrict.setObjectName("lbDistrict")
        self.horizontalLayout_7.addWidget(self.lbDistrict)
        self.leDistrict = QtWidgets.QLineEdit(self.groupBox_3)
        self.leDistrict.setReadOnly(True)
        self.leDistrict.setObjectName("leDistrict")
        self.horizontalLayout_7.addWidget(self.leDistrict)
        self.lbCity = QtWidgets.QLabel(self.groupBox_3)
        self.lbCity.setObjectName("lbCity")
        self.horizontalLayout_7.addWidget(self.lbCity)
        self.leCity = QtWidgets.QLineEdit(self.groupBox_3)
        self.leCity.setReadOnly(True)
        self.leCity.setObjectName("leCity")
        self.horizontalLayout_7.addWidget(self.leCity)
        self.lbState = QtWidgets.QLabel(self.groupBox_3)
        self.lbState.setObjectName("lbState")
        self.horizontalLayout_7.addWidget(self.lbState)
        self.leState = QtWidgets.QLineEdit(self.groupBox_3)
        self.leState.setMaxLength(2)
        self.leState.setReadOnly(True)
        self.leState.setObjectName("leState")
        self.horizontalLayout_7.addWidget(self.leState)
        self.lbContry = QtWidgets.QLabel(self.groupBox_3)
        self.lbContry.setObjectName("lbContry")
        self.horizontalLayout_7.addWidget(self.lbContry)
        self.leContry = QtWidgets.QLineEdit(self.groupBox_3)
        self.leContry.setReadOnly(True)
        self.leContry.setObjectName("leContry")
        self.horizontalLayout_7.addWidget(self.leContry)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.verticalLayout_5.addWidget(self.groupBox_3)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setMouseTracking(False)
        self.tab_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tab_2.setAcceptDrops(False)
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.lbType = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbType.sizePolicy().hasHeightForWidth())
        self.lbType.setSizePolicy(sizePolicy)
        self.lbType.setObjectName("lbType")
        self.horizontalLayout_10.addWidget(self.lbType)
        self.cbType = QtWidgets.QComboBox(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbType.sizePolicy().hasHeightForWidth())
        self.cbType.setSizePolicy(sizePolicy)
        self.cbType.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cbType.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.cbType.setEditable(True)
        self.cbType.setObjectName("cbType")
        self.cbType.addItem("")
        self.cbType.setItemText(0, "")
        self.cbType.addItem("")
        self.cbType.addItem("")
        self.cbType.addItem("")
        self.cbType.addItem("")
        self.cbType.addItem("")
        self.cbType.addItem("")
        self.cbType.addItem("")
        self.cbType.addItem("")
        self.cbType.addItem("")
        self.cbType.addItem("")
        self.cbType.addItem("")
        self.cbType.addItem("")
        self.cbType.addItem("")
        self.cbType.addItem("")
        self.cbType.addItem("")
        self.cbType.addItem("")
        self.cbType.addItem("")
        self.cbType.setItemText(17, "")
        self.horizontalLayout_10.addWidget(self.cbType)
        self.lbBrand = QtWidgets.QLabel(self.tab_2)
        self.lbBrand.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lbBrand.setObjectName("lbBrand")
        self.horizontalLayout_10.addWidget(self.lbBrand)
        self.cbBrand = QtWidgets.QComboBox(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbBrand.sizePolicy().hasHeightForWidth())
        self.cbBrand.setSizePolicy(sizePolicy)
        self.cbBrand.setEditable(True)
        self.cbBrand.setObjectName("cbBrand")
        self.cbBrand.addItem("")
        self.cbBrand.setItemText(0, "")
        self.cbBrand.addItem("")
        self.cbBrand.addItem("")
        self.cbBrand.addItem("")
        self.cbBrand.addItem("")
        self.cbBrand.addItem("")
        self.cbBrand.addItem("")
        self.cbBrand.addItem("")
        self.cbBrand.addItem("")
        self.cbBrand.addItem("")
        self.cbBrand.addItem("")
        self.cbBrand.addItem("")
        self.cbBrand.addItem("")
        self.cbBrand.addItem("")
        self.cbBrand.addItem("")
        self.cbBrand.addItem("")
        self.cbBrand.addItem("")
        self.cbBrand.addItem("")
        self.cbBrand.addItem("")
        self.cbBrand.addItem("")
        self.cbBrand.addItem("")
        self.cbBrand.addItem("")
        self.cbBrand.addItem("")
        self.cbBrand.addItem("")
        self.cbBrand.addItem("")
        self.cbBrand.addItem("")
        self.cbBrand.addItem("")
        self.cbBrand.addItem("")
        self.cbBrand.addItem("")
        self.cbBrand.addItem("")
        self.cbBrand.addItem("")
        self.cbBrand.addItem("")
        self.cbBrand.addItem("")
        self.cbBrand.addItem("")
        self.cbBrand.addItem("")
        self.cbBrand.addItem("")
        self.cbBrand.addItem("")
        self.cbBrand.addItem("")
        self.cbBrand.addItem("")
        self.cbBrand.addItem("")
        self.cbBrand.addItem("")
        self.cbBrand.addItem("")
        self.cbBrand.addItem("")
        self.cbBrand.addItem("")
        self.cbBrand.addItem("")
        self.cbBrand.addItem("")
        self.cbBrand.addItem("")
        self.cbBrand.addItem("")
        self.cbBrand.addItem("")
        self.cbBrand.setItemText(48, "")
        self.horizontalLayout_10.addWidget(self.cbBrand)
        self.lbModel = QtWidgets.QLabel(self.tab_2)
        self.lbModel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lbModel.setObjectName("lbModel")
        self.horizontalLayout_10.addWidget(self.lbModel)
        self.leModel = QtWidgets.QLineEdit(self.tab_2)
        self.leModel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.leModel.setObjectName("leModel")
        self.horizontalLayout_10.addWidget(self.leModel)
        self.lbColor = QtWidgets.QLabel(self.tab_2)
        self.lbColor.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lbColor.setObjectName("lbColor")
        self.horizontalLayout_10.addWidget(self.lbColor)
        self.leColor = QtWidgets.QLineEdit(self.tab_2)
        self.leColor.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.leColor.setObjectName("leColor")
        self.horizontalLayout_10.addWidget(self.leColor)
        self.verticalLayout_6.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.lbNs = QtWidgets.QLabel(self.tab_2)
        self.lbNs.setObjectName("lbNs")
        self.horizontalLayout_11.addWidget(self.lbNs)
        self.leNs = QtWidgets.QLineEdit(self.tab_2)
        self.leNs.setObjectName("leNs")
        self.horizontalLayout_11.addWidget(self.leNs)
        self.lbBarCode = QtWidgets.QLabel(self.tab_2)
        self.lbBarCode.setObjectName("lbBarCode")
        self.horizontalLayout_11.addWidget(self.lbBarCode)
        self.leBarCode = QtWidgets.QLineEdit(self.tab_2)
        self.leBarCode.setObjectName("leBarCode")
        self.horizontalLayout_11.addWidget(self.leBarCode)
        self.verticalLayout_6.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.lbImei1 = QtWidgets.QLabel(self.tab_2)
        self.lbImei1.setObjectName("lbImei1")
        self.horizontalLayout_24.addWidget(self.lbImei1)
        self.leImei1 = QtWidgets.QLineEdit(self.tab_2)
        self.leImei1.setMaxLength(15)
        self.leImei1.setObjectName("leImei1")
        self.horizontalLayout_24.addWidget(self.leImei1)
        self.lbImei2 = QtWidgets.QLabel(self.tab_2)
        self.lbImei2.setObjectName("lbImei2")
        self.horizontalLayout_24.addWidget(self.lbImei2)
        self.leImei2 = QtWidgets.QLineEdit(self.tab_2)
        self.leImei2.setObjectName("leImei2")
        self.horizontalLayout_24.addWidget(self.leImei2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.lbAcessories = QtWidgets.QLabel(self.tab_2)
        self.lbAcessories.setObjectName("lbAcessories")
        self.horizontalLayout_13.addWidget(self.lbAcessories)
        self.leAcessories = QtWidgets.QLineEdit(self.tab_2)
        self.leAcessories.setObjectName("leAcessories")
        self.horizontalLayout_13.addWidget(self.leAcessories)
        self.verticalLayout_6.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.lbDeviceStatus = QtWidgets.QLabel(self.tab_2)
        self.lbDeviceStatus.setObjectName("lbDeviceStatus")
        self.horizontalLayout_14.addWidget(self.lbDeviceStatus)
        self.leDeviceStatus = QtWidgets.QLineEdit(self.tab_2)
        self.leDeviceStatus.setObjectName("leDeviceStatus")
        self.horizontalLayout_14.addWidget(self.leDeviceStatus)
        self.verticalLayout_6.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.lbDefect = QtWidgets.QLabel(self.tab_2)
        self.lbDefect.setObjectName("lbDefect")
        self.horizontalLayout_15.addWidget(self.lbDefect)
        self.leDefect = QtWidgets.QLineEdit(self.tab_2)
        self.leDefect.setObjectName("leDefect")
        self.horizontalLayout_15.addWidget(self.leDefect)
        self.verticalLayout_6.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.lbObs1 = QtWidgets.QLabel(self.tab_2)
        self.lbObs1.setObjectName("lbObs1")
        self.horizontalLayout_17.addWidget(self.lbObs1)
        self.teObs1 = QtWidgets.QTextEdit(self.tab_2)
        self.teObs1.setObjectName("teObs1")
        self.horizontalLayout_17.addWidget(self.teObs1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_17)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.lbDefectsFound = QtWidgets.QLabel(self.tab_4)
        self.lbDefectsFound.setObjectName("lbDefectsFound")
        self.horizontalLayout_18.addWidget(self.lbDefectsFound)
        self.leDefectsFound = QtWidgets.QLineEdit(self.tab_4)
        self.leDefectsFound.setObjectName("leDefectsFound")
        self.horizontalLayout_18.addWidget(self.leDefectsFound)
        self.verticalLayout_8.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.lbServiceDone = QtWidgets.QLabel(self.tab_4)
        self.lbServiceDone.setObjectName("lbServiceDone")
        self.horizontalLayout_19.addWidget(self.lbServiceDone)
        self.leServiceDone = QtWidgets.QLineEdit(self.tab_4)
        self.leServiceDone.setObjectName("leServiceDone")
        self.horizontalLayout_19.addWidget(self.leServiceDone)
        self.verticalLayout_8.addLayout(self.horizontalLayout_19)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.lbBudgetTable = QtWidgets.QLabel(self.tab_4)
        self.lbBudgetTable.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.lbBudgetTable.setFont(font)
        self.lbBudgetTable.setAlignment(QtCore.Qt.AlignCenter)
        self.lbBudgetTable.setObjectName("lbBudgetTable")
        self.verticalLayout_9.addWidget(self.lbBudgetTable)
        self.twBudget = QtWidgets.QTableWidget(self.tab_4)
        self.twBudget.setMaximumSize(QtCore.QSize(16777215, 100))
        self.twBudget.setAlternatingRowColors(False)
        self.twBudget.setObjectName("twBudget")
        self.twBudget.setColumnCount(4)
        self.twBudget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.twBudget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.twBudget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.twBudget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.twBudget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.twBudget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.twBudget.setItem(0, 3, item)
        self.twBudget.horizontalHeader().setStretchLastSection(True)
        self.twBudget.verticalHeader().setCascadingSectionResizes(False)
        self.twBudget.verticalHeader().setSortIndicatorShown(False)
        self.twBudget.verticalHeader().setStretchLastSection(True)
        self.verticalLayout_9.addWidget(self.twBudget)
        self.verticalLayout_8.addLayout(self.verticalLayout_9)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.lbPartsValue = QtWidgets.QLabel(self.tab_4)
        self.lbPartsValue.setObjectName("lbPartsValue")
        self.horizontalLayout_21.addWidget(self.lbPartsValue)
        self.lePartsValue = QtWidgets.QLineEdit(self.tab_4)
        self.lePartsValue.setObjectName("lePartsValue")
        self.horizontalLayout_21.addWidget(self.lePartsValue)
        self.lbServiceValue = QtWidgets.QLabel(self.tab_4)
        self.lbServiceValue.setObjectName("lbServiceValue")
        self.horizontalLayout_21.addWidget(self.lbServiceValue)
        self.leServiceValue = QtWidgets.QLineEdit(self.tab_4)
        self.leServiceValue.setObjectName("leServiceValue")
        self.horizontalLayout_21.addWidget(self.leServiceValue)
        self.lbTotalValue = QtWidgets.QLabel(self.tab_4)
        self.lbTotalValue.setObjectName("lbTotalValue")
        self.horizontalLayout_21.addWidget(self.lbTotalValue)
        self.leTotalValue = QtWidgets.QLineEdit(self.tab_4)
        self.leTotalValue.setObjectName("leTotalValue")
        self.horizontalLayout_21.addWidget(self.leTotalValue)
        self.verticalLayout_8.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.lbObs2 = QtWidgets.QLabel(self.tab_4)
        self.lbObs2.setObjectName("lbObs2")
        self.horizontalLayout_20.addWidget(self.lbObs2)
        self.leObs2 = QtWidgets.QLineEdit(self.tab_4)
        self.leObs2.setObjectName("leObs2")
        self.horizontalLayout_20.addWidget(self.leObs2)
        self.verticalLayout_8.addLayout(self.horizontalLayout_20)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.lbTotalSpent = QtWidgets.QLabel(self.tab_3)
        self.lbTotalSpent.setGeometry(QtCore.QRect(210, 390, 71, 78))
        self.lbTotalSpent.setObjectName("lbTotalSpent")
        self.leTotalSpent = QtWidgets.QLineEdit(self.tab_3)
        self.leTotalSpent.setGeometry(QtCore.QRect(290, 410, 179, 32))
        self.leTotalSpent.setObjectName("leTotalSpent")
        self.twCliHistory = QtWidgets.QTableWidget(self.tab_3)
        self.twCliHistory.setGeometry(QtCore.QRect(45, 11, 681, 371))
        self.twCliHistory.setObjectName("twCliHistory")
        self.twCliHistory.setColumnCount(0)
        self.twCliHistory.setRowCount(0)
        self.tabWidget.addTab(self.tab_3, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.rbAnalysis = QtWidgets.QRadioButton(SOrderEdit)
        self.rbAnalysis.setChecked(True)
        self.rbAnalysis.setObjectName("rbAnalysis")
        self.buttonGroup_2 = QtWidgets.QButtonGroup(SOrderEdit)
        self.buttonGroup_2.setObjectName("buttonGroup_2")
        self.buttonGroup_2.addButton(self.rbAnalysis)
        self.horizontalLayout_22.addWidget(self.rbAnalysis)
        self.rbBudget = QtWidgets.QRadioButton(SOrderEdit)
        self.rbBudget.setObjectName("rbBudget")
        self.buttonGroup_2.addButton(self.rbBudget)
        self.horizontalLayout_22.addWidget(self.rbBudget)
        self.rbApproved = QtWidgets.QRadioButton(SOrderEdit)
        self.rbApproved.setObjectName("rbApproved")
        self.buttonGroup_2.addButton(self.rbApproved)
        self.horizontalLayout_22.addWidget(self.rbApproved)
        self.rbRefused = QtWidgets.QRadioButton(SOrderEdit)
        self.rbRefused.setObjectName("rbRefused")
        self.buttonGroup_2.addButton(self.rbRefused)
        self.horizontalLayout_22.addWidget(self.rbRefused)
        self.rbFixed = QtWidgets.QRadioButton(SOrderEdit)
        self.rbFixed.setObjectName("rbFixed")
        self.buttonGroup_2.addButton(self.rbFixed)
        self.horizontalLayout_22.addWidget(self.rbFixed)
        self.rbDelivery = QtWidgets.QRadioButton(SOrderEdit)
        self.rbDelivery.setObjectName("rbDelivery")
        self.buttonGroup_2.addButton(self.rbDelivery)
        self.horizontalLayout_22.addWidget(self.rbDelivery)
        self.verticalLayout.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.pbSave = QtWidgets.QPushButton(SOrderEdit)
        self.pbSave.setObjectName("pbSave")
        self.horizontalLayout_9.addWidget(self.pbSave)
        self.pbPrint = QtWidgets.QPushButton(SOrderEdit)
        self.pbPrint.setEnabled(False)
        self.pbPrint.setObjectName("pbPrint")
        self.horizontalLayout_9.addWidget(self.pbPrint)
        self.pbNewOs = QtWidgets.QPushButton(SOrderEdit)
        self.pbNewOs.setEnabled(False)
        self.pbNewOs.setObjectName("pbNewOs")
        self.horizontalLayout_9.addWidget(self.pbNewOs)
        self.pbDelivery = QtWidgets.QPushButton(SOrderEdit)
        self.pbDelivery.setEnabled(False)
        self.pbDelivery.setObjectName("pbDelivery")
        self.horizontalLayout_9.addWidget(self.pbDelivery)
        self.pbExit = QtWidgets.QPushButton(SOrderEdit)
        self.pbExit.setObjectName("pbExit")
        self.horizontalLayout_9.addWidget(self.pbExit)
        self.verticalLayout.addLayout(self.horizontalLayout_9)

        self.retranslateUi(SOrderEdit)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.pbExit, QtCore.SIGNAL("clicked()"), SOrderEdit.reject)
        QtCore.QMetaObject.connectSlotsByName(SOrderEdit)

    def retranslateUi(self, SOrderEdit):
        SOrderEdit.setWindowTitle(QtWidgets.QApplication.translate("SOrderEdit", "Ordem de Serviço", None, -1))
        self.lbWindow.setText(QtWidgets.QApplication.translate("SOrderEdit", "Ordem de Serviço", None, -1))
        self.lbOs.setText(QtWidgets.QApplication.translate("SOrderEdit", "OS:", None, -1))
        self.lbStatus1.setText(QtWidgets.QApplication.translate("SOrderEdit", "Status:", None, -1))
        self.lbStatus2.setText(QtWidgets.QApplication.translate("SOrderEdit", "Em análise", None, -1))
        self.lbEntryDate.setText(QtWidgets.QApplication.translate("SOrderEdit", "Data de entrada:", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("SOrderEdit", "Data de alteração", None, -1))
        self.lbOutDate.setText(QtWidgets.QApplication.translate("SOrderEdit", "Data de saída:", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("SOrderEdit", "Identificação ", None, -1))
        self.lbCodCli.setText(QtWidgets.QApplication.translate("SOrderEdit", "Código do cliente:", None, -1))
        self.lbName.setText(QtWidgets.QApplication.translate("SOrderEdit", "Nome:", None, -1))
        self.lbBirth.setText(QtWidgets.QApplication.translate("SOrderEdit", "Nascimento:", None, -1))
        self.dtBirth.setDisplayFormat(QtWidgets.QApplication.translate("SOrderEdit", "dd/MM/yyyy", None, -1))
        self.lbSex.setText(QtWidgets.QApplication.translate("SOrderEdit", "Sexo:", None, -1))
        self.rbM.setText(QtWidgets.QApplication.translate("SOrderEdit", "M", None, -1))
        self.rbF.setText(QtWidgets.QApplication.translate("SOrderEdit", "F", None, -1))
        self.lbCpfCnpj.setText(QtWidgets.QApplication.translate("SOrderEdit", "CPF:", None, -1))
        self.lbRgIe.setText(QtWidgets.QApplication.translate("SOrderEdit", "RG:", None, -1))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("SOrderEdit", "Contato", None, -1))
        self.lbCell1.setText(QtWidgets.QApplication.translate("SOrderEdit", "Celular 1", None, -1))
        self.cbCell1.setItemText(1, QtWidgets.QApplication.translate("SOrderEdit", "Vivo", None, -1))
        self.cbCell1.setItemText(2, QtWidgets.QApplication.translate("SOrderEdit", "Tim", None, -1))
        self.cbCell1.setItemText(3, QtWidgets.QApplication.translate("SOrderEdit", "Nextel", None, -1))
        self.cbCell1.setItemText(4, QtWidgets.QApplication.translate("SOrderEdit", "Oi", None, -1))
        self.cbCell1.setItemText(5, QtWidgets.QApplication.translate("SOrderEdit", "Claro", None, -1))
        self.lbCell2.setText(QtWidgets.QApplication.translate("SOrderEdit", "Celular 2:", None, -1))
        self.cbCell2.setItemText(1, QtWidgets.QApplication.translate("SOrderEdit", "Nextel", None, -1))
        self.cbCell2.setItemText(2, QtWidgets.QApplication.translate("SOrderEdit", "Vivo", None, -1))
        self.cbCell2.setItemText(3, QtWidgets.QApplication.translate("SOrderEdit", "Tim", None, -1))
        self.cbCell2.setItemText(4, QtWidgets.QApplication.translate("SOrderEdit", "Oi", None, -1))
        self.cbCell2.setItemText(5, QtWidgets.QApplication.translate("SOrderEdit", "Claro", None, -1))
        self.lbTel.setText(QtWidgets.QApplication.translate("SOrderEdit", "Telefone:", None, -1))
        self.lbEmail.setText(QtWidgets.QApplication.translate("SOrderEdit", "E-mail:", None, -1))
        self.groupBox_3.setTitle(QtWidgets.QApplication.translate("SOrderEdit", "Endereço", None, -1))
        self.lbAdress.setText(QtWidgets.QApplication.translate("SOrderEdit", "Logradouro:", None, -1))
        self.lbNumber.setText(QtWidgets.QApplication.translate("SOrderEdit", "Nº", None, -1))
        self.lbAdress2.setText(QtWidgets.QApplication.translate("SOrderEdit", "Complemento:", None, -1))
        self.lbCep.setText(QtWidgets.QApplication.translate("SOrderEdit", "CEP:", None, -1))
        self.lbDistrict.setText(QtWidgets.QApplication.translate("SOrderEdit", "Bairro:", None, -1))
        self.lbCity.setText(QtWidgets.QApplication.translate("SOrderEdit", "Cidade:", None, -1))
        self.lbState.setText(QtWidgets.QApplication.translate("SOrderEdit", "Estado:", None, -1))
        self.lbContry.setText(QtWidgets.QApplication.translate("SOrderEdit", "País:", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtWidgets.QApplication.translate("SOrderEdit", "Dados do cliente", None, -1))
        self.lbType.setText(QtWidgets.QApplication.translate("SOrderEdit", "Tipo", None, -1))
        self.cbType.setItemText(1, QtWidgets.QApplication.translate("SOrderEdit", "Notebook", None, -1))
        self.cbType.setItemText(2, QtWidgets.QApplication.translate("SOrderEdit", "Smartphone", None, -1))
        self.cbType.setItemText(3, QtWidgets.QApplication.translate("SOrderEdit", "Tablet", None, -1))
        self.cbType.setItemText(4, QtWidgets.QApplication.translate("SOrderEdit", "Desktop", None, -1))
        self.cbType.setItemText(5, QtWidgets.QApplication.translate("SOrderEdit", "Netbook", None, -1))
        self.cbType.setItemText(6, QtWidgets.QApplication.translate("SOrderEdit", "Celular", None, -1))
        self.cbType.setItemText(7, QtWidgets.QApplication.translate("SOrderEdit", "Pendrive", None, -1))
        self.cbType.setItemText(8, QtWidgets.QApplication.translate("SOrderEdit", "HD", None, -1))
        self.cbType.setItemText(9, QtWidgets.QApplication.translate("SOrderEdit", "Monitor", None, -1))
        self.cbType.setItemText(10, QtWidgets.QApplication.translate("SOrderEdit", "TV", None, -1))
        self.cbType.setItemText(11, QtWidgets.QApplication.translate("SOrderEdit", "Video Game", None, -1))
        self.cbType.setItemText(12, QtWidgets.QApplication.translate("SOrderEdit", "Brinquedo", None, -1))
        self.cbType.setItemText(13, QtWidgets.QApplication.translate("SOrderEdit", "DVD Player", None, -1))
        self.cbType.setItemText(14, QtWidgets.QApplication.translate("SOrderEdit", "Roteador", None, -1))
        self.cbType.setItemText(15, QtWidgets.QApplication.translate("SOrderEdit", "Controle", None, -1))
        self.cbType.setItemText(16, QtWidgets.QApplication.translate("SOrderEdit", "Não Especificado", None, -1))
        self.lbBrand.setText(QtWidgets.QApplication.translate("SOrderEdit", "Marca:", None, -1))
        self.cbBrand.setItemText(1, QtWidgets.QApplication.translate("SOrderEdit", "Acer", None, -1))
        self.cbBrand.setItemText(2, QtWidgets.QApplication.translate("SOrderEdit", "Alcatel", None, -1))
        self.cbBrand.setItemText(3, QtWidgets.QApplication.translate("SOrderEdit", "Q-Mobile", None, -1))
        self.cbBrand.setItemText(4, QtWidgets.QApplication.translate("SOrderEdit", "Xiaomi", None, -1))
        self.cbBrand.setItemText(5, QtWidgets.QApplication.translate("SOrderEdit", "OnePlus", None, -1))
        self.cbBrand.setItemText(6, QtWidgets.QApplication.translate("SOrderEdit", "Apple", None, -1))
        self.cbBrand.setItemText(7, QtWidgets.QApplication.translate("SOrderEdit", "Asus", None, -1))
        self.cbBrand.setItemText(8, QtWidgets.QApplication.translate("SOrderEdit", "BLU", None, -1))
        self.cbBrand.setItemText(9, QtWidgets.QApplication.translate("SOrderEdit", "CCE", None, -1))
        self.cbBrand.setItemText(10, QtWidgets.QApplication.translate("SOrderEdit", "Compaq", None, -1))
        self.cbBrand.setItemText(11, QtWidgets.QApplication.translate("SOrderEdit", "Dell", None, -1))
        self.cbBrand.setItemText(12, QtWidgets.QApplication.translate("SOrderEdit", "DL", None, -1))
        self.cbBrand.setItemText(13, QtWidgets.QApplication.translate("SOrderEdit", "D-Link", None, -1))
        self.cbBrand.setItemText(14, QtWidgets.QApplication.translate("SOrderEdit", "Huawei", None, -1))
        self.cbBrand.setItemText(15, QtWidgets.QApplication.translate("SOrderEdit", "Quantum", None, -1))
        self.cbBrand.setItemText(16, QtWidgets.QApplication.translate("SOrderEdit", "BlackBerry", None, -1))
        self.cbBrand.setItemText(17, QtWidgets.QApplication.translate("SOrderEdit", "Gateway", None, -1))
        self.cbBrand.setItemText(18, QtWidgets.QApplication.translate("SOrderEdit", "ZTE", None, -1))
        self.cbBrand.setItemText(19, QtWidgets.QApplication.translate("SOrderEdit", "Multilaser", None, -1))
        self.cbBrand.setItemText(20, QtWidgets.QApplication.translate("SOrderEdit", "HTC", None, -1))
        self.cbBrand.setItemText(21, QtWidgets.QApplication.translate("SOrderEdit", "Bright", None, -1))
        self.cbBrand.setItemText(22, QtWidgets.QApplication.translate("SOrderEdit", "Itautec", None, -1))
        self.cbBrand.setItemText(23, QtWidgets.QApplication.translate("SOrderEdit", "Microsoft", None, -1))
        self.cbBrand.setItemText(24, QtWidgets.QApplication.translate("SOrderEdit", "Microboard", None, -1))
        self.cbBrand.setItemText(25, QtWidgets.QApplication.translate("SOrderEdit", "Samsung", None, -1))
        self.cbBrand.setItemText(26, QtWidgets.QApplication.translate("SOrderEdit", "LG", None, -1))
        self.cbBrand.setItemText(27, QtWidgets.QApplication.translate("SOrderEdit", "Motorola", None, -1))
        self.cbBrand.setItemText(28, QtWidgets.QApplication.translate("SOrderEdit", "Nokia", None, -1))
        self.cbBrand.setItemText(29, QtWidgets.QApplication.translate("SOrderEdit", "Lenovo", None, -1))
        self.cbBrand.setItemText(30, QtWidgets.QApplication.translate("SOrderEdit", "Seagate", None, -1))
        self.cbBrand.setItemText(31, QtWidgets.QApplication.translate("SOrderEdit", "WD", None, -1))
        self.cbBrand.setItemText(32, QtWidgets.QApplication.translate("SOrderEdit", "Hitachi", None, -1))
        self.cbBrand.setItemText(33, QtWidgets.QApplication.translate("SOrderEdit", "Positivo", None, -1))
        self.cbBrand.setItemText(34, QtWidgets.QApplication.translate("SOrderEdit", "Navicity", None, -1))
        self.cbBrand.setItemText(35, QtWidgets.QApplication.translate("SOrderEdit", "Qbex", None, -1))
        self.cbBrand.setItemText(36, QtWidgets.QApplication.translate("SOrderEdit", "HP", None, -1))
        self.cbBrand.setItemText(37, QtWidgets.QApplication.translate("SOrderEdit", "Every", None, -1))
        self.cbBrand.setItemText(38, QtWidgets.QApplication.translate("SOrderEdit", "Lenoxx", None, -1))
        self.cbBrand.setItemText(39, QtWidgets.QApplication.translate("SOrderEdit", "Sony", None, -1))
        self.cbBrand.setItemText(40, QtWidgets.QApplication.translate("SOrderEdit", "Sony Ericsson", None, -1))
        self.cbBrand.setItemText(41, QtWidgets.QApplication.translate("SOrderEdit", "Siemens", None, -1))
        self.cbBrand.setItemText(42, QtWidgets.QApplication.translate("SOrderEdit", "Semp Toshiba", None, -1))
        self.cbBrand.setItemText(43, QtWidgets.QApplication.translate("SOrderEdit", "Semp", None, -1))
        self.cbBrand.setItemText(44, QtWidgets.QApplication.translate("SOrderEdit", "Toshiba", None, -1))
        self.cbBrand.setItemText(45, QtWidgets.QApplication.translate("SOrderEdit", "How", None, -1))
        self.cbBrand.setItemText(46, QtWidgets.QApplication.translate("SOrderEdit", "TP-Link", None, -1))
        self.cbBrand.setItemText(47, QtWidgets.QApplication.translate("SOrderEdit", "Não Especificado", None, -1))
        self.lbModel.setText(QtWidgets.QApplication.translate("SOrderEdit", "Modelo:", None, -1))
        self.lbColor.setText(QtWidgets.QApplication.translate("SOrderEdit", "Cor:", None, -1))
        self.lbNs.setText(QtWidgets.QApplication.translate("SOrderEdit", "N/S:", None, -1))
        self.lbBarCode.setText(QtWidgets.QApplication.translate("SOrderEdit", "Cod. barras:", None, -1))
        self.lbImei1.setText(QtWidgets.QApplication.translate("SOrderEdit", "IMEI 1:", None, -1))
        self.lbImei2.setText(QtWidgets.QApplication.translate("SOrderEdit", "IMEI 2", None, -1))
        self.lbAcessories.setText(QtWidgets.QApplication.translate("SOrderEdit", "Acessórios:", None, -1))
        self.lbDeviceStatus.setText(QtWidgets.QApplication.translate("SOrderEdit", "Estado do equipamento:", None, -1))
        self.lbDefect.setText(QtWidgets.QApplication.translate("SOrderEdit", "Defeito reclamado:", None, -1))
        self.lbObs1.setText(QtWidgets.QApplication.translate("SOrderEdit", "Observação:", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtWidgets.QApplication.translate("SOrderEdit", "Dados do equipamento", None, -1))
        self.lbDefectsFound.setText(QtWidgets.QApplication.translate("SOrderEdit", "Defeito encontrado:", None, -1))
        self.lbServiceDone.setText(QtWidgets.QApplication.translate("SOrderEdit", "Serviço executado:", None, -1))
        self.lbBudgetTable.setText(QtWidgets.QApplication.translate("SOrderEdit", "Peças utilizadas no conserto:", None, -1))
        self.twBudget.verticalHeaderItem(0).setText(QtWidgets.QApplication.translate("SOrderEdit", "1", None, -1))
        self.twBudget.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("SOrderEdit", "Descrição", None, -1))
        self.twBudget.horizontalHeaderItem(1).setText(QtWidgets.QApplication.translate("SOrderEdit", "Valor unitário", None, -1))
        self.twBudget.horizontalHeaderItem(2).setText(QtWidgets.QApplication.translate("SOrderEdit", "Quantidade", None, -1))
        self.twBudget.horizontalHeaderItem(3).setText(QtWidgets.QApplication.translate("SOrderEdit", "Sub Total", None, -1))
        __sortingEnabled = self.twBudget.isSortingEnabled()
        self.twBudget.setSortingEnabled(False)
        self.twBudget.setSortingEnabled(__sortingEnabled)
        self.lbPartsValue.setText(QtWidgets.QApplication.translate("SOrderEdit", "Valor peças:", None, -1))
        self.lbServiceValue.setText(QtWidgets.QApplication.translate("SOrderEdit", "Valor serviço:", None, -1))
        self.lbTotalValue.setText(QtWidgets.QApplication.translate("SOrderEdit", "Total:", None, -1))
        self.lbObs2.setText(QtWidgets.QApplication.translate("SOrderEdit", "Observações:", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtWidgets.QApplication.translate("SOrderEdit", "Orçamento", None, -1))
        self.lbTotalSpent.setText(QtWidgets.QApplication.translate("SOrderEdit", "Total gasto:", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtWidgets.QApplication.translate("SOrderEdit", "Histórico do cliente", None, -1))
        self.rbAnalysis.setText(QtWidgets.QApplication.translate("SOrderEdit", "Em análise", None, -1))
        self.rbBudget.setText(QtWidgets.QApplication.translate("SOrderEdit", "Com orçamento", None, -1))
        self.rbApproved.setText(QtWidgets.QApplication.translate("SOrderEdit", "Aprovado", None, -1))
        self.rbRefused.setText(QtWidgets.QApplication.translate("SOrderEdit", "Rec&usado", None, -1))
        self.rbFixed.setText(QtWidgets.QApplication.translate("SOrderEdit", "Consertado", None, -1))
        self.rbDelivery.setText(QtWidgets.QApplication.translate("SOrderEdit", "Devo&lver", None, -1))
        self.pbSave.setText(QtWidgets.QApplication.translate("SOrderEdit", "Salvar", None, -1))
        self.pbPrint.setText(QtWidgets.QApplication.translate("SOrderEdit", "Imprimir", None, -1))
        self.pbNewOs.setText(QtWidgets.QApplication.translate("SOrderEdit", "Nova OS", None, -1))
        self.pbDelivery.setText(QtWidgets.QApplication.translate("SOrderEdit", "Entregar", None, -1))
        self.pbExit.setText(QtWidgets.QApplication.translate("SOrderEdit", "Sair", None, -1))

