# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sorder.ui',
# licensing of 'sorder.ui' applies.
#
# Created: Sun Dec  9 17:49:29 2018
#      by: pyside2-uic  running on PySide2 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_SOrderEdit(object):
    def setupUi(self, SOrderEdit):
        SOrderEdit.setObjectName("SOrderEdit")
        SOrderEdit.resize(794, 607)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("IMG/logoblack.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SOrderEdit.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(SOrderEdit)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_33 = QtWidgets.QLabel(SOrderEdit)
        self.label_33.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_12.addWidget(self.label_33)
        self.label_34 = QtWidgets.QLabel(SOrderEdit)
        self.label_34.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label_34.setText("")
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_12.addWidget(self.label_34)
        self.label_17 = QtWidgets.QLabel(SOrderEdit)
        self.label_17.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_17.setFont(font)
        self.label_17.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_12.addWidget(self.label_17)
        self.label_23 = QtWidgets.QLabel(SOrderEdit)
        self.label_23.setMaximumSize(QtCore.QSize(30, 16777215))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_12.addWidget(self.label_23)
        self.label_29 = QtWidgets.QLabel(SOrderEdit)
        self.label_29.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_29.setText("")
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_12.addWidget(self.label_29)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.tabWidget = QtWidgets.QTabWidget(SOrderEdit)
        self.tabWidget.setFocusPolicy(QtCore.Qt.TabFocus)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setBaseSize(QtCore.QSize(0, 0))
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_4.addWidget(self.lineEdit)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.dateEdit = QtWidgets.QDateEdit(self.groupBox)
        self.dateEdit.setObjectName("dateEdit")
        self.horizontalLayout_4.addWidget(self.dateEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_16 = QtWidgets.QLabel(self.groupBox)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout.addWidget(self.label_16)
        self.radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout.addWidget(self.radioButton_2)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout.addWidget(self.lineEdit_2)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout.addWidget(self.lineEdit_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_32 = QtWidgets.QLabel(self.groupBox)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_16.addWidget(self.label_32)
        self.dateEdit_4 = QtWidgets.QDateEdit(self.groupBox)
        self.dateEdit_4.setFrame(False)
        self.dateEdit_4.setReadOnly(True)
        self.dateEdit_4.setCurrentSectionIndex(0)
        self.dateEdit_4.setObjectName("dateEdit_4")
        self.horizontalLayout_16.addWidget(self.dateEdit_4)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_16)
        self.verticalLayout_5.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_2.addWidget(self.lineEdit_4)
        self.comboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox.setMaximumSize(QtCore.QSize(70, 16777215))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayout_2.addWidget(self.lineEdit_5)
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_2.setMaximumSize(QtCore.QSize(70, 16777215))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_6.setMaximumSize(QtCore.QSize(120, 16777215))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.horizontalLayout_5.addWidget(self.lineEdit_6)
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_5.addWidget(self.label_8)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_7.sizePolicy().hasHeightForWidth())
        self.lineEdit_7.setSizePolicy(sizePolicy)
        self.lineEdit_7.setMaximumSize(QtCore.QSize(1677215, 16777215))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.horizontalLayout_5.addWidget(self.lineEdit_7)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.verticalLayout_5.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_14 = QtWidgets.QLabel(self.groupBox_3)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_8.addWidget(self.label_14)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_13.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.horizontalLayout_8.addWidget(self.lineEdit_13)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_3.addWidget(self.label_9)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.horizontalLayout_3.addWidget(self.lineEdit_8)
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_3.addWidget(self.label_10)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_9.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.horizontalLayout_3.addWidget(self.lineEdit_9)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_6.addWidget(self.label_11)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.horizontalLayout_6.addWidget(self.lineEdit_10)
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_6.addWidget(self.label_12)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.horizontalLayout_6.addWidget(self.lineEdit_11)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_7.addWidget(self.label_13)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_12.setMaxLength(2)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.horizontalLayout_7.addWidget(self.lineEdit_12)
        self.label_15 = QtWidgets.QLabel(self.groupBox_3)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_7.addWidget(self.label_15)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.horizontalLayout_7.addWidget(self.lineEdit_14)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.verticalLayout_5.addWidget(self.groupBox_3)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setMouseTracking(False)
        self.tab_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tab_2.setAcceptDrops(False)
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_18 = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_10.addWidget(self.label_18)
        self.comboBox_3 = QtWidgets.QComboBox(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_3.sizePolicy().hasHeightForWidth())
        self.comboBox_3.setSizePolicy(sizePolicy)
        self.comboBox_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.comboBox_3.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.setItemText(13, "")
        self.horizontalLayout_10.addWidget(self.comboBox_3)
        self.label_19 = QtWidgets.QLabel(self.tab_2)
        self.label_19.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_10.addWidget(self.label_19)
        self.comboBox_4 = QtWidgets.QComboBox(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_4.sizePolicy().hasHeightForWidth())
        self.comboBox_4.setSizePolicy(sizePolicy)
        self.comboBox_4.setEditable(False)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.setItemText(28, "")
        self.horizontalLayout_10.addWidget(self.comboBox_4)
        self.label_20 = QtWidgets.QLabel(self.tab_2)
        self.label_20.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_10.addWidget(self.label_20)
        self.lineEdit_17 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_17.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.horizontalLayout_10.addWidget(self.lineEdit_17)
        self.label_21 = QtWidgets.QLabel(self.tab_2)
        self.label_21.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_10.addWidget(self.label_21)
        self.lineEdit_18 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_18.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.horizontalLayout_10.addWidget(self.lineEdit_18)
        self.verticalLayout_6.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_30 = QtWidgets.QLabel(self.tab_2)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_11.addWidget(self.label_30)
        self.lineEdit_20 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_20.setMaxLength(15)
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.horizontalLayout_11.addWidget(self.lineEdit_20)
        self.label_22 = QtWidgets.QLabel(self.tab_2)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_11.addWidget(self.label_22)
        self.lineEdit_19 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.horizontalLayout_11.addWidget(self.lineEdit_19)
        self.label_24 = QtWidgets.QLabel(self.tab_2)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_11.addWidget(self.label_24)
        self.lineEdit_21 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.horizontalLayout_11.addWidget(self.lineEdit_21)
        self.verticalLayout_6.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_25 = QtWidgets.QLabel(self.tab_2)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_13.addWidget(self.label_25)
        self.lineEdit_15 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.horizontalLayout_13.addWidget(self.lineEdit_15)
        self.verticalLayout_6.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_26 = QtWidgets.QLabel(self.tab_2)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_14.addWidget(self.label_26)
        self.lineEdit_16 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.horizontalLayout_14.addWidget(self.lineEdit_16)
        self.verticalLayout_6.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_27 = QtWidgets.QLabel(self.tab_2)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_15.addWidget(self.label_27)
        self.lineEdit_22 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.horizontalLayout_15.addWidget(self.lineEdit_22)
        self.verticalLayout_6.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_42 = QtWidgets.QLabel(self.tab_2)
        self.label_42.setObjectName("label_42")
        self.horizontalLayout_17.addWidget(self.label_42)
        self.textEdit = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout_17.addWidget(self.textEdit)
        self.verticalLayout_6.addLayout(self.horizontalLayout_17)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_28 = QtWidgets.QLabel(self.tab_4)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_23.addWidget(self.label_28)
        self.dateEdit_2 = QtWidgets.QDateEdit(self.tab_4)
        self.dateEdit_2.setReadOnly(True)
        self.dateEdit_2.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.horizontalLayout_23.addWidget(self.dateEdit_2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem3)
        self.label_31 = QtWidgets.QLabel(self.tab_4)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_23.addWidget(self.label_31)
        self.dateEdit_3 = QtWidgets.QDateEdit(self.tab_4)
        self.dateEdit_3.setFrame(True)
        self.dateEdit_3.setReadOnly(True)
        self.dateEdit_3.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.dateEdit_3.setObjectName("dateEdit_3")
        self.horizontalLayout_23.addWidget(self.dateEdit_3)
        self.verticalLayout_8.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_35 = QtWidgets.QLabel(self.tab_4)
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_18.addWidget(self.label_35)
        self.lineEdit_23 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.horizontalLayout_18.addWidget(self.lineEdit_23)
        self.verticalLayout_8.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_36 = QtWidgets.QLabel(self.tab_4)
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_19.addWidget(self.label_36)
        self.lineEdit_24 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.horizontalLayout_19.addWidget(self.lineEdit_24)
        self.verticalLayout_8.addLayout(self.horizontalLayout_19)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_37 = QtWidgets.QLabel(self.tab_4)
        self.label_37.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_37.setFont(font)
        self.label_37.setAlignment(QtCore.Qt.AlignCenter)
        self.label_37.setObjectName("label_37")
        self.verticalLayout_9.addWidget(self.label_37)
        self.tableWidget_2 = QtWidgets.QTableWidget(self.tab_4)
        self.tableWidget_2.setMaximumSize(QtCore.QSize(16777215, 100))
        self.tableWidget_2.setAlternatingRowColors(False)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(4)
        self.tableWidget_2.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        self.tableWidget_2.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_2.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget_2.verticalHeader().setSortIndicatorShown(False)
        self.tableWidget_2.verticalHeader().setStretchLastSection(True)
        self.verticalLayout_9.addWidget(self.tableWidget_2)
        self.verticalLayout_8.addLayout(self.verticalLayout_9)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_38 = QtWidgets.QLabel(self.tab_4)
        self.label_38.setObjectName("label_38")
        self.horizontalLayout_21.addWidget(self.label_38)
        self.lineEdit_25 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.horizontalLayout_21.addWidget(self.lineEdit_25)
        self.label_40 = QtWidgets.QLabel(self.tab_4)
        self.label_40.setObjectName("label_40")
        self.horizontalLayout_21.addWidget(self.label_40)
        self.lineEdit_26 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.horizontalLayout_21.addWidget(self.lineEdit_26)
        self.label_41 = QtWidgets.QLabel(self.tab_4)
        self.label_41.setObjectName("label_41")
        self.horizontalLayout_21.addWidget(self.label_41)
        self.lineEdit_27 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.horizontalLayout_21.addWidget(self.lineEdit_27)
        self.verticalLayout_8.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.radioButton_3 = QtWidgets.QRadioButton(self.tab_4)
        self.radioButton_3.setChecked(True)
        self.radioButton_3.setObjectName("radioButton_3")
        self.horizontalLayout_22.addWidget(self.radioButton_3)
        self.radioButton_4 = QtWidgets.QRadioButton(self.tab_4)
        self.radioButton_4.setObjectName("radioButton_4")
        self.horizontalLayout_22.addWidget(self.radioButton_4)
        self.radioButton_5 = QtWidgets.QRadioButton(self.tab_4)
        self.radioButton_5.setObjectName("radioButton_5")
        self.horizontalLayout_22.addWidget(self.radioButton_5)
        self.radioButton_6 = QtWidgets.QRadioButton(self.tab_4)
        self.radioButton_6.setObjectName("radioButton_6")
        self.horizontalLayout_22.addWidget(self.radioButton_6)
        self.radioButton_8 = QtWidgets.QRadioButton(self.tab_4)
        self.radioButton_8.setObjectName("radioButton_8")
        self.horizontalLayout_22.addWidget(self.radioButton_8)
        self.radioButton_7 = QtWidgets.QRadioButton(self.tab_4)
        self.radioButton_7.setObjectName("radioButton_7")
        self.horizontalLayout_22.addWidget(self.radioButton_7)
        self.verticalLayout_8.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_39 = QtWidgets.QLabel(self.tab_4)
        self.label_39.setObjectName("label_39")
        self.horizontalLayout_20.addWidget(self.label_39)
        self.lineEdit_28 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.horizontalLayout_20.addWidget(self.lineEdit_28)
        self.verticalLayout_8.addLayout(self.horizontalLayout_20)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tableView = QtWidgets.QTableView(self.tab_3)
        self.tableView.setGeometry(QtCore.QRect(5, 11, 761, 421))
        self.tableView.setObjectName("tableView")
        self.tabWidget.addTab(self.tab_3, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.pushButton = QtWidgets.QPushButton(SOrderEdit)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_9.addWidget(self.pushButton)
        self.pushButton_4 = QtWidgets.QPushButton(SOrderEdit)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_9.addWidget(self.pushButton_4)
        self.pushButton_3 = QtWidgets.QPushButton(SOrderEdit)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_9.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(SOrderEdit)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_9.addWidget(self.pushButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout_9)

        self.retranslateUi(SOrderEdit)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(SOrderEdit)

    def retranslateUi(self, SOrderEdit):
        SOrderEdit.setWindowTitle(QtWidgets.QApplication.translate("SOrderEdit", "Dialog", None, -1))
        self.label_33.setText(QtWidgets.QApplication.translate("SOrderEdit", "Status:", None, -1))
        self.label_17.setText(QtWidgets.QApplication.translate("SOrderEdit", "Ordem de Serviço", None, -1))
        self.label_23.setText(QtWidgets.QApplication.translate("SOrderEdit", "OS:", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("SOrderEdit", "Identificação ", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("SOrderEdit", "Nome:", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("SOrderEdit", "Nascimento:", None, -1))
        self.dateEdit.setDisplayFormat(QtWidgets.QApplication.translate("SOrderEdit", "dd/MM/yyyy", None, -1))
        self.label_16.setText(QtWidgets.QApplication.translate("SOrderEdit", "Sexo:", None, -1))
        self.radioButton.setText(QtWidgets.QApplication.translate("SOrderEdit", "M", None, -1))
        self.radioButton_2.setText(QtWidgets.QApplication.translate("SOrderEdit", "F", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("SOrderEdit", "CPF:", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("SOrderEdit", "RG:", None, -1))
        self.label_32.setText(QtWidgets.QApplication.translate("SOrderEdit", "Data de Cadastro:", None, -1))
        self.dateEdit_4.setDisplayFormat(QtWidgets.QApplication.translate("SOrderEdit", "dd/MM/yyyy", None, -1))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("SOrderEdit", "Contato", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("SOrderEdit", "Celular 1", None, -1))
        self.comboBox.setItemText(0, QtWidgets.QApplication.translate("SOrderEdit", "Oi", None, -1))
        self.comboBox.setItemText(1, QtWidgets.QApplication.translate("SOrderEdit", "Vivo", None, -1))
        self.comboBox.setItemText(2, QtWidgets.QApplication.translate("SOrderEdit", "Tim", None, -1))
        self.comboBox.setItemText(3, QtWidgets.QApplication.translate("SOrderEdit", "Claro", None, -1))
        self.comboBox.setItemText(4, QtWidgets.QApplication.translate("SOrderEdit", "Nextel", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("SOrderEdit", "Celular 2:", None, -1))
        self.comboBox_2.setItemText(0, QtWidgets.QApplication.translate("SOrderEdit", "Vivo", None, -1))
        self.comboBox_2.setItemText(1, QtWidgets.QApplication.translate("SOrderEdit", "Tim", None, -1))
        self.comboBox_2.setItemText(2, QtWidgets.QApplication.translate("SOrderEdit", "Claro", None, -1))
        self.comboBox_2.setItemText(3, QtWidgets.QApplication.translate("SOrderEdit", "Nextel", None, -1))
        self.comboBox_2.setItemText(4, QtWidgets.QApplication.translate("SOrderEdit", "Oi", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("SOrderEdit", "Telefone:", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("SOrderEdit", "E-mail:", None, -1))
        self.groupBox_3.setTitle(QtWidgets.QApplication.translate("SOrderEdit", "Endereço", None, -1))
        self.label_14.setText(QtWidgets.QApplication.translate("SOrderEdit", "CEP:", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("SOrderEdit", "Logradouro:", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("SOrderEdit", "Nº", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("SOrderEdit", "Bairro:", None, -1))
        self.label_12.setText(QtWidgets.QApplication.translate("SOrderEdit", "Cidade:", None, -1))
        self.label_13.setText(QtWidgets.QApplication.translate("SOrderEdit", "Estado:", None, -1))
        self.label_15.setText(QtWidgets.QApplication.translate("SOrderEdit", "País:", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtWidgets.QApplication.translate("SOrderEdit", "Dados do Cliente", None, -1))
        self.label_18.setText(QtWidgets.QApplication.translate("SOrderEdit", "Equipamento:", None, -1))
        self.comboBox_3.setItemText(0, QtWidgets.QApplication.translate("SOrderEdit", "Smartphone", None, -1))
        self.comboBox_3.setItemText(1, QtWidgets.QApplication.translate("SOrderEdit", "Notebook", None, -1))
        self.comboBox_3.setItemText(2, QtWidgets.QApplication.translate("SOrderEdit", "Tablet", None, -1))
        self.comboBox_3.setItemText(3, QtWidgets.QApplication.translate("SOrderEdit", "Netbook", None, -1))
        self.comboBox_3.setItemText(4, QtWidgets.QApplication.translate("SOrderEdit", "Celular", None, -1))
        self.comboBox_3.setItemText(5, QtWidgets.QApplication.translate("SOrderEdit", "Monitor", None, -1))
        self.comboBox_3.setItemText(6, QtWidgets.QApplication.translate("SOrderEdit", "TV", None, -1))
        self.comboBox_3.setItemText(7, QtWidgets.QApplication.translate("SOrderEdit", "Video Game", None, -1))
        self.comboBox_3.setItemText(8, QtWidgets.QApplication.translate("SOrderEdit", "Brinquedo", None, -1))
        self.comboBox_3.setItemText(9, QtWidgets.QApplication.translate("SOrderEdit", "DVD Player", None, -1))
        self.comboBox_3.setItemText(10, QtWidgets.QApplication.translate("SOrderEdit", "Roteador", None, -1))
        self.comboBox_3.setItemText(11, QtWidgets.QApplication.translate("SOrderEdit", "Controle", None, -1))
        self.comboBox_3.setItemText(12, QtWidgets.QApplication.translate("SOrderEdit", "Não Especificado", None, -1))
        self.label_19.setText(QtWidgets.QApplication.translate("SOrderEdit", "Marca:", None, -1))
        self.comboBox_4.setItemText(0, QtWidgets.QApplication.translate("SOrderEdit", "Apple", None, -1))
        self.comboBox_4.setItemText(1, QtWidgets.QApplication.translate("SOrderEdit", "Samsung", None, -1))
        self.comboBox_4.setItemText(2, QtWidgets.QApplication.translate("SOrderEdit", "LG", None, -1))
        self.comboBox_4.setItemText(3, QtWidgets.QApplication.translate("SOrderEdit", "Motorola", None, -1))
        self.comboBox_4.setItemText(4, QtWidgets.QApplication.translate("SOrderEdit", "Nokia", None, -1))
        self.comboBox_4.setItemText(5, QtWidgets.QApplication.translate("SOrderEdit", "Lenovo", None, -1))
        self.comboBox_4.setItemText(6, QtWidgets.QApplication.translate("SOrderEdit", "Asus", None, -1))
        self.comboBox_4.setItemText(7, QtWidgets.QApplication.translate("SOrderEdit", "Positivo", None, -1))
        self.comboBox_4.setItemText(8, QtWidgets.QApplication.translate("SOrderEdit", "DL", None, -1))
        self.comboBox_4.setItemText(9, QtWidgets.QApplication.translate("SOrderEdit", "Navicity", None, -1))
        self.comboBox_4.setItemText(10, QtWidgets.QApplication.translate("SOrderEdit", "Qbex", None, -1))
        self.comboBox_4.setItemText(11, QtWidgets.QApplication.translate("SOrderEdit", "Dell", None, -1))
        self.comboBox_4.setItemText(12, QtWidgets.QApplication.translate("SOrderEdit", "HP", None, -1))
        self.comboBox_4.setItemText(13, QtWidgets.QApplication.translate("SOrderEdit", "Every", None, -1))
        self.comboBox_4.setItemText(14, QtWidgets.QApplication.translate("SOrderEdit", "Lenoxx", None, -1))
        self.comboBox_4.setItemText(15, QtWidgets.QApplication.translate("SOrderEdit", "CCE", None, -1))
        self.comboBox_4.setItemText(16, QtWidgets.QApplication.translate("SOrderEdit", "Compaq", None, -1))
        self.comboBox_4.setItemText(17, QtWidgets.QApplication.translate("SOrderEdit", "Sony", None, -1))
        self.comboBox_4.setItemText(18, QtWidgets.QApplication.translate("SOrderEdit", "Sony Ericsson", None, -1))
        self.comboBox_4.setItemText(19, QtWidgets.QApplication.translate("SOrderEdit", "Siemens", None, -1))
        self.comboBox_4.setItemText(20, QtWidgets.QApplication.translate("SOrderEdit", "Semp Toshiba", None, -1))
        self.comboBox_4.setItemText(21, QtWidgets.QApplication.translate("SOrderEdit", "Semp", None, -1))
        self.comboBox_4.setItemText(22, QtWidgets.QApplication.translate("SOrderEdit", "Toshiba", None, -1))
        self.comboBox_4.setItemText(23, QtWidgets.QApplication.translate("SOrderEdit", "Acer", None, -1))
        self.comboBox_4.setItemText(24, QtWidgets.QApplication.translate("SOrderEdit", "How", None, -1))
        self.comboBox_4.setItemText(25, QtWidgets.QApplication.translate("SOrderEdit", "D-Link", None, -1))
        self.comboBox_4.setItemText(26, QtWidgets.QApplication.translate("SOrderEdit", "TP-Link", None, -1))
        self.comboBox_4.setItemText(27, QtWidgets.QApplication.translate("SOrderEdit", "Não Especificado", None, -1))
        self.label_20.setText(QtWidgets.QApplication.translate("SOrderEdit", "Modelo:", None, -1))
        self.label_21.setText(QtWidgets.QApplication.translate("SOrderEdit", "Cor:", None, -1))
        self.label_30.setText(QtWidgets.QApplication.translate("SOrderEdit", "IMEI:", None, -1))
        self.label_22.setText(QtWidgets.QApplication.translate("SOrderEdit", "N/S:", None, -1))
        self.label_24.setText(QtWidgets.QApplication.translate("SOrderEdit", "Cod. Barras:", None, -1))
        self.label_25.setText(QtWidgets.QApplication.translate("SOrderEdit", "Acessórios:", None, -1))
        self.label_26.setText(QtWidgets.QApplication.translate("SOrderEdit", "Estado do Equipamento:", None, -1))
        self.label_27.setText(QtWidgets.QApplication.translate("SOrderEdit", "Defeito Reclamado:", None, -1))
        self.label_42.setText(QtWidgets.QApplication.translate("SOrderEdit", "Observação:", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtWidgets.QApplication.translate("SOrderEdit", "Dados do Equipamento", None, -1))
        self.label_28.setText(QtWidgets.QApplication.translate("SOrderEdit", "Data de entrada:", None, -1))
        self.dateEdit_2.setDisplayFormat(QtWidgets.QApplication.translate("SOrderEdit", "dd/MM/yyyy", None, -1))
        self.label_31.setText(QtWidgets.QApplication.translate("SOrderEdit", "Data de Saída:", None, -1))
        self.dateEdit_3.setDisplayFormat(QtWidgets.QApplication.translate("SOrderEdit", "dd/MM/yyyy", None, -1))
        self.label_35.setText(QtWidgets.QApplication.translate("SOrderEdit", "Defeitos encontrados:", None, -1))
        self.label_36.setText(QtWidgets.QApplication.translate("SOrderEdit", "Serviço executado:", None, -1))
        self.label_37.setText(QtWidgets.QApplication.translate("SOrderEdit", "Peças utilizadas no conserto:", None, -1))
        self.tableWidget_2.verticalHeaderItem(0).setText(QtWidgets.QApplication.translate("SOrderEdit", "1", None, -1))
        self.tableWidget_2.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("SOrderEdit", "Descrição", None, -1))
        self.tableWidget_2.horizontalHeaderItem(1).setText(QtWidgets.QApplication.translate("SOrderEdit", "Quantidade", None, -1))
        self.tableWidget_2.horizontalHeaderItem(2).setText(QtWidgets.QApplication.translate("SOrderEdit", "Valor un", None, -1))
        self.tableWidget_2.horizontalHeaderItem(3).setText(QtWidgets.QApplication.translate("SOrderEdit", "Sub Total", None, -1))
        self.label_38.setText(QtWidgets.QApplication.translate("SOrderEdit", "Valor peças:", None, -1))
        self.label_40.setText(QtWidgets.QApplication.translate("SOrderEdit", "Valor Serviço:", None, -1))
        self.label_41.setText(QtWidgets.QApplication.translate("SOrderEdit", "Total:", None, -1))
        self.radioButton_3.setText(QtWidgets.QApplication.translate("SOrderEdit", "Em Orçamento", None, -1))
        self.radioButton_4.setText(QtWidgets.QApplication.translate("SOrderEdit", "A&guardando Aprovação", None, -1))
        self.radioButton_5.setText(QtWidgets.QApplication.translate("SOrderEdit", "Aprovado", None, -1))
        self.radioButton_6.setText(QtWidgets.QApplication.translate("SOrderEdit", "Rec&usado", None, -1))
        self.radioButton_8.setText(QtWidgets.QApplication.translate("SOrderEdit", "Consertado", None, -1))
        self.radioButton_7.setText(QtWidgets.QApplication.translate("SOrderEdit", "Devo&lver", None, -1))
        self.label_39.setText(QtWidgets.QApplication.translate("SOrderEdit", "Observações:", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtWidgets.QApplication.translate("SOrderEdit", "Orçamento", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtWidgets.QApplication.translate("SOrderEdit", "Histórico do Cliente", None, -1))
        self.pushButton.setText(QtWidgets.QApplication.translate("SOrderEdit", "Salvar", None, -1))
        self.pushButton_4.setText(QtWidgets.QApplication.translate("SOrderEdit", "Imprimir", None, -1))
        self.pushButton_3.setText(QtWidgets.QApplication.translate("SOrderEdit", "Nova OS", None, -1))
        self.pushButton_2.setText(QtWidgets.QApplication.translate("SOrderEdit", "Entregar", None, -1))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SOrderEdit = QtWidgets.QDialog()
    ui = Ui_SOrderEdit()
    ui.setupUi(SOrderEdit)
    SOrderEdit.show()
    sys.exit(app.exec_())

