# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'clients.ui',
# licensing of 'clients.ui' applies.
#
# Created: Sat Mar  9 16:10:01 2019
#      by: pyside2-uic  running on PySide2 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_ClientEdit(object):
    def setupUi(self, ClientEdit):
        ClientEdit.setObjectName("ClientEdit")
        ClientEdit.resize(622, 628)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        ClientEdit.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("IMG/logoblack.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ClientEdit.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(ClientEdit)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbMenuCli = QtWidgets.QLabel(ClientEdit)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.lbMenuCli.setFont(font)
        self.lbMenuCli.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbMenuCli.setAlignment(QtCore.Qt.AlignCenter)
        self.lbMenuCli.setObjectName("lbMenuCli")
        self.verticalLayout.addWidget(self.lbMenuCli)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbCodCli = QtWidgets.QLabel(ClientEdit)
        self.lbCodCli.setObjectName("lbCodCli")
        self.horizontalLayout.addWidget(self.lbCodCli)
        self.leCodCli = QtWidgets.QLineEdit(ClientEdit)
        self.leCodCli.setMaximumSize(QtCore.QSize(130, 16777215))
        self.leCodCli.setObjectName("leCodCli")
        self.horizontalLayout.addWidget(self.leCodCli)
        self.lbdatecadcli = QtWidgets.QLabel(ClientEdit)
        self.lbdatecadcli.setObjectName("lbdatecadcli")
        self.horizontalLayout.addWidget(self.lbdatecadcli)
        self.dateEdit_2 = QtWidgets.QDateEdit(ClientEdit)
        self.dateEdit_2.setEnabled(False)
        self.dateEdit_2.setWrapping(False)
        self.dateEdit_2.setReadOnly(True)
        self.dateEdit_2.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.dateEdit_2.setSpecialValueText("")
        self.dateEdit_2.setTimeSpec(QtCore.Qt.LocalTime)
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.horizontalLayout.addWidget(self.dateEdit_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gb1 = QtWidgets.QGroupBox(ClientEdit)
        self.gb1.setBaseSize(QtCore.QSize(0, 0))
        self.gb1.setFlat(False)
        self.gb1.setObjectName("gb1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.gb1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.hl1 = QtWidgets.QHBoxLayout()
        self.hl1.setObjectName("hl1")
        self.label = QtWidgets.QLabel(self.gb1)
        self.label.setObjectName("label")
        self.hl1.addWidget(self.label)
        self.radioButton = QtWidgets.QRadioButton(self.gb1)
        self.radioButton.setCheckable(True)
        self.radioButton.setChecked(True)
        self.radioButton.setAutoExclusive(False)
        self.radioButton.setObjectName("radioButton")
        self.buttonGroup = QtWidgets.QButtonGroup(ClientEdit)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.radioButton)
        self.hl1.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.gb1)
        self.radioButton_2.setObjectName("radioButton_2")
        self.buttonGroup.addButton(self.radioButton_2)
        self.hl1.addWidget(self.radioButton_2)
        self.checkBox = QtWidgets.QCheckBox(self.gb1)
        self.checkBox.setObjectName("checkBox")
        self.hl1.addWidget(self.checkBox)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hl1.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.hl1)
        self.hl2 = QtWidgets.QHBoxLayout()
        self.hl2.setObjectName("hl2")
        self.lbName = QtWidgets.QLabel(self.gb1)
        self.lbName.setObjectName("lbName")
        self.hl2.addWidget(self.lbName)
        self.leName = QtWidgets.QLineEdit(self.gb1)
        self.leName.setObjectName("leName")
        self.hl2.addWidget(self.leName)
        self.lbborn = QtWidgets.QLabel(self.gb1)
        self.lbborn.setObjectName("lbborn")
        self.hl2.addWidget(self.lbborn)
        self.dateEdit = QtWidgets.QDateEdit(self.gb1)
        self.dateEdit.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.hl2.addWidget(self.dateEdit)
        self.verticalLayout_2.addLayout(self.hl2)
        self.hl3 = QtWidgets.QHBoxLayout()
        self.hl3.setObjectName("hl3")
        self.lbSex = QtWidgets.QLabel(self.gb1)
        self.lbSex.setObjectName("lbSex")
        self.hl3.addWidget(self.lbSex)
        self.rbM = QtWidgets.QRadioButton(self.gb1)
        self.rbM.setChecked(True)
        self.rbM.setObjectName("rbM")
        self.buttonGroup_2 = QtWidgets.QButtonGroup(ClientEdit)
        self.buttonGroup_2.setObjectName("buttonGroup_2")
        self.buttonGroup_2.addButton(self.rbM)
        self.hl3.addWidget(self.rbM)
        self.rbF = QtWidgets.QRadioButton(self.gb1)
        self.rbF.setObjectName("rbF")
        self.buttonGroup_2.addButton(self.rbF)
        self.hl3.addWidget(self.rbF)
        self.lbCpf = QtWidgets.QLabel(self.gb1)
        self.lbCpf.setObjectName("lbCpf")
        self.hl3.addWidget(self.lbCpf)
        self.leCpf = QtWidgets.QLineEdit(self.gb1)
        self.leCpf.setObjectName("leCpf")
        self.hl3.addWidget(self.leCpf)
        self.lbRg = QtWidgets.QLabel(self.gb1)
        self.lbRg.setObjectName("lbRg")
        self.hl3.addWidget(self.lbRg)
        self.leRg = QtWidgets.QLineEdit(self.gb1)
        self.leRg.setObjectName("leRg")
        self.hl3.addWidget(self.leRg)
        self.verticalLayout_2.addLayout(self.hl3)
        self.verticalLayout.addWidget(self.gb1)
        self.gb2 = QtWidgets.QGroupBox(ClientEdit)
        self.gb2.setObjectName("gb2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.gb2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.hl4 = QtWidgets.QHBoxLayout()
        self.hl4.setObjectName("hl4")
        self.lbCell1 = QtWidgets.QLabel(self.gb2)
        self.lbCell1.setObjectName("lbCell1")
        self.hl4.addWidget(self.lbCell1)
        self.leCell1 = QtWidgets.QLineEdit(self.gb2)
        self.leCell1.setObjectName("leCell1")
        self.hl4.addWidget(self.leCell1)
        self.cbCell1 = QtWidgets.QComboBox(self.gb2)
        self.cbCell1.setMaximumSize(QtCore.QSize(70, 16777215))
        self.cbCell1.setObjectName("cbCell1")
        self.cbCell1.addItem("")
        self.cbCell1.addItem("")
        self.cbCell1.addItem("")
        self.cbCell1.addItem("")
        self.cbCell1.addItem("")
        self.hl4.addWidget(self.cbCell1)
        self.lbCell2 = QtWidgets.QLabel(self.gb2)
        self.lbCell2.setObjectName("lbCell2")
        self.hl4.addWidget(self.lbCell2)
        self.leCell2 = QtWidgets.QLineEdit(self.gb2)
        self.leCell2.setObjectName("leCell2")
        self.hl4.addWidget(self.leCell2)
        self.cbCell2 = QtWidgets.QComboBox(self.gb2)
        self.cbCell2.setMaximumSize(QtCore.QSize(70, 16777215))
        self.cbCell2.setObjectName("cbCell2")
        self.cbCell2.addItem("")
        self.cbCell2.addItem("")
        self.cbCell2.addItem("")
        self.cbCell2.addItem("")
        self.cbCell2.addItem("")
        self.hl4.addWidget(self.cbCell2)
        self.verticalLayout_3.addLayout(self.hl4)
        self.hl5 = QtWidgets.QHBoxLayout()
        self.hl5.setObjectName("hl5")
        self.lbTel = QtWidgets.QLabel(self.gb2)
        self.lbTel.setObjectName("lbTel")
        self.hl5.addWidget(self.lbTel)
        self.leTel = QtWidgets.QLineEdit(self.gb2)
        self.leTel.setMaximumSize(QtCore.QSize(120, 16777215))
        self.leTel.setObjectName("leTel")
        self.hl5.addWidget(self.leTel)
        self.lbMail = QtWidgets.QLabel(self.gb2)
        self.lbMail.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lbMail.setObjectName("lbMail")
        self.hl5.addWidget(self.lbMail)
        self.leMail = QtWidgets.QLineEdit(self.gb2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leMail.sizePolicy().hasHeightForWidth())
        self.leMail.setSizePolicy(sizePolicy)
        self.leMail.setMaximumSize(QtCore.QSize(1677215, 16777215))
        self.leMail.setObjectName("leMail")
        self.hl5.addWidget(self.leMail)
        self.verticalLayout_3.addLayout(self.hl5)
        self.verticalLayout.addWidget(self.gb2)
        self.gb3 = QtWidgets.QGroupBox(ClientEdit)
        self.gb3.setObjectName("gb3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.gb3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.hl6 = QtWidgets.QHBoxLayout()
        self.hl6.setObjectName("hl6")
        self.lbCep = QtWidgets.QLabel(self.gb3)
        self.lbCep.setObjectName("lbCep")
        self.hl6.addWidget(self.lbCep)
        self.leCep = QtWidgets.QLineEdit(self.gb3)
        self.leCep.setMaximumSize(QtCore.QSize(150, 16777215))
        self.leCep.setObjectName("leCep")
        self.hl6.addWidget(self.leCep)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hl6.addItem(spacerItem2)
        self.verticalLayout_4.addLayout(self.hl6)
        self.hl7 = QtWidgets.QHBoxLayout()
        self.hl7.setObjectName("hl7")
        self.lbStreet = QtWidgets.QLabel(self.gb3)
        self.lbStreet.setObjectName("lbStreet")
        self.hl7.addWidget(self.lbStreet)
        self.leStreet = QtWidgets.QLineEdit(self.gb3)
        self.leStreet.setObjectName("leStreet")
        self.hl7.addWidget(self.leStreet)
        self.verticalLayout_4.addLayout(self.hl7)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lbNumber = QtWidgets.QLabel(self.gb3)
        self.lbNumber.setObjectName("lbNumber")
        self.horizontalLayout_2.addWidget(self.lbNumber)
        self.leNumber = QtWidgets.QLineEdit(self.gb3)
        self.leNumber.setMaximumSize(QtCore.QSize(60, 16777215))
        self.leNumber.setObjectName("leNumber")
        self.horizontalLayout_2.addWidget(self.leNumber)
        self.lbComp = QtWidgets.QLabel(self.gb3)
        self.lbComp.setObjectName("lbComp")
        self.horizontalLayout_2.addWidget(self.lbComp)
        self.leComp = QtWidgets.QLineEdit(self.gb3)
        self.leComp.setObjectName("leComp")
        self.horizontalLayout_2.addWidget(self.leComp)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.hl8 = QtWidgets.QHBoxLayout()
        self.hl8.setObjectName("hl8")
        self.lbDistrict = QtWidgets.QLabel(self.gb3)
        self.lbDistrict.setObjectName("lbDistrict")
        self.hl8.addWidget(self.lbDistrict)
        self.leDistrict = QtWidgets.QLineEdit(self.gb3)
        self.leDistrict.setObjectName("leDistrict")
        self.hl8.addWidget(self.leDistrict)
        self.lbCity = QtWidgets.QLabel(self.gb3)
        self.lbCity.setObjectName("lbCity")
        self.hl8.addWidget(self.lbCity)
        self.leCity = QtWidgets.QLineEdit(self.gb3)
        self.leCity.setObjectName("leCity")
        self.hl8.addWidget(self.leCity)
        self.verticalLayout_4.addLayout(self.hl8)
        self.hl9 = QtWidgets.QHBoxLayout()
        self.hl9.setObjectName("hl9")
        self.lbState = QtWidgets.QLabel(self.gb3)
        self.lbState.setObjectName("lbState")
        self.hl9.addWidget(self.lbState)
        self.leState = QtWidgets.QLineEdit(self.gb3)
        self.leState.setObjectName("leState")
        self.hl9.addWidget(self.leState)
        self.lbContry = QtWidgets.QLabel(self.gb3)
        self.lbContry.setObjectName("lbContry")
        self.hl9.addWidget(self.lbContry)
        self.leContry = QtWidgets.QLineEdit(self.gb3)
        self.leContry.setObjectName("leContry")
        self.hl9.addWidget(self.leContry)
        self.verticalLayout_4.addLayout(self.hl9)
        self.verticalLayout.addWidget(self.gb3)
        self.hl10 = QtWidgets.QHBoxLayout()
        self.hl10.setObjectName("hl10")
        self.pbSave = QtWidgets.QPushButton(ClientEdit)
        self.pbSave.setObjectName("pbSave")
        self.hl10.addWidget(self.pbSave)
        self.pbDelete = QtWidgets.QPushButton(ClientEdit)
        self.pbDelete.setEnabled(False)
        self.pbDelete.setObjectName("pbDelete")
        self.hl10.addWidget(self.pbDelete)
        self.pbNew = QtWidgets.QPushButton(ClientEdit)
        self.pbNew.setEnabled(False)
        self.pbNew.setObjectName("pbNew")
        self.hl10.addWidget(self.pbNew)
        self.pbExit = QtWidgets.QPushButton(ClientEdit)
        self.pbExit.setObjectName("pbExit")
        self.hl10.addWidget(self.pbExit)
        self.verticalLayout.addLayout(self.hl10)

        self.retranslateUi(ClientEdit)
        QtCore.QMetaObject.connectSlotsByName(ClientEdit)
        ClientEdit.setTabOrder(self.leName, self.dateEdit)
        ClientEdit.setTabOrder(self.dateEdit, self.rbM)
        ClientEdit.setTabOrder(self.rbM, self.rbF)
        ClientEdit.setTabOrder(self.rbF, self.leCpf)
        ClientEdit.setTabOrder(self.leCpf, self.leRg)
        ClientEdit.setTabOrder(self.leRg, self.leCell1)
        ClientEdit.setTabOrder(self.leCell1, self.cbCell1)
        ClientEdit.setTabOrder(self.cbCell1, self.leCell2)
        ClientEdit.setTabOrder(self.leCell2, self.cbCell2)
        ClientEdit.setTabOrder(self.cbCell2, self.leTel)
        ClientEdit.setTabOrder(self.leTel, self.leMail)
        ClientEdit.setTabOrder(self.leMail, self.leCep)
        ClientEdit.setTabOrder(self.leCep, self.leStreet)
        ClientEdit.setTabOrder(self.leStreet, self.leDistrict)
        ClientEdit.setTabOrder(self.leDistrict, self.leCity)
        ClientEdit.setTabOrder(self.leCity, self.leState)
        ClientEdit.setTabOrder(self.leState, self.leContry)
        ClientEdit.setTabOrder(self.leContry, self.pbSave)
        ClientEdit.setTabOrder(self.pbSave, self.pbDelete)
        ClientEdit.setTabOrder(self.pbDelete, self.pbNew)
        ClientEdit.setTabOrder(self.pbNew, self.pbExit)
        ClientEdit.setTabOrder(self.pbExit, self.dateEdit_2)
        ClientEdit.setTabOrder(self.dateEdit_2, self.checkBox)

    def retranslateUi(self, ClientEdit):
        ClientEdit.setWindowTitle(QtWidgets.QApplication.translate("ClientEdit", "Menu Clientes", None, -1))
        self.lbMenuCli.setText(QtWidgets.QApplication.translate("ClientEdit", "Menu Clientes", None, -1))
        self.lbCodCli.setText(QtWidgets.QApplication.translate("ClientEdit", "Cod. Cliente:", None, -1))
        self.lbdatecadcli.setText(QtWidgets.QApplication.translate("ClientEdit", "Cadastrado em:", None, -1))
        self.dateEdit_2.setDisplayFormat(QtWidgets.QApplication.translate("ClientEdit", "dd/MM/yy", None, -1))
        self.gb1.setTitle(QtWidgets.QApplication.translate("ClientEdit", "Identificação ", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("ClientEdit", "Tipo de Cliente:", None, -1))
        self.radioButton.setText(QtWidgets.QApplication.translate("ClientEdit", "Pessoa F&ísica", None, -1))
        self.radioButton_2.setText(QtWidgets.QApplication.translate("ClientEdit", "Pessoa &Jurídica", None, -1))
        self.checkBox.setText(QtWidgets.QApplication.translate("ClientEdit", "Bloquear?", None, -1))
        self.lbName.setText(QtWidgets.QApplication.translate("ClientEdit", "Nome:", None, -1))
        self.lbborn.setText(QtWidgets.QApplication.translate("ClientEdit", "Nascimento:", None, -1))
        self.lbSex.setText(QtWidgets.QApplication.translate("ClientEdit", "Sexo:", None, -1))
        self.rbM.setText(QtWidgets.QApplication.translate("ClientEdit", "M", None, -1))
        self.rbF.setText(QtWidgets.QApplication.translate("ClientEdit", "F", None, -1))
        self.lbCpf.setText(QtWidgets.QApplication.translate("ClientEdit", "CPF:", None, -1))
        self.lbRg.setText(QtWidgets.QApplication.translate("ClientEdit", "RG:", None, -1))
        self.gb2.setTitle(QtWidgets.QApplication.translate("ClientEdit", "Contato", None, -1))
        self.lbCell1.setText(QtWidgets.QApplication.translate("ClientEdit", "Celular 1", None, -1))
        self.cbCell1.setItemText(0, QtWidgets.QApplication.translate("ClientEdit", "Oi", None, -1))
        self.cbCell1.setItemText(1, QtWidgets.QApplication.translate("ClientEdit", "Vivo", None, -1))
        self.cbCell1.setItemText(2, QtWidgets.QApplication.translate("ClientEdit", "Tim", None, -1))
        self.cbCell1.setItemText(3, QtWidgets.QApplication.translate("ClientEdit", "Claro", None, -1))
        self.cbCell1.setItemText(4, QtWidgets.QApplication.translate("ClientEdit", "Nextel", None, -1))
        self.lbCell2.setText(QtWidgets.QApplication.translate("ClientEdit", "Celular 2:", None, -1))
        self.cbCell2.setItemText(0, QtWidgets.QApplication.translate("ClientEdit", "Vivo", None, -1))
        self.cbCell2.setItemText(1, QtWidgets.QApplication.translate("ClientEdit", "Tim", None, -1))
        self.cbCell2.setItemText(2, QtWidgets.QApplication.translate("ClientEdit", "Claro", None, -1))
        self.cbCell2.setItemText(3, QtWidgets.QApplication.translate("ClientEdit", "Nextel", None, -1))
        self.cbCell2.setItemText(4, QtWidgets.QApplication.translate("ClientEdit", "Oi", None, -1))
        self.lbTel.setText(QtWidgets.QApplication.translate("ClientEdit", "Telefone:", None, -1))
        self.lbMail.setText(QtWidgets.QApplication.translate("ClientEdit", "E-mail:", None, -1))
        self.gb3.setTitle(QtWidgets.QApplication.translate("ClientEdit", "Endereço", None, -1))
        self.lbCep.setText(QtWidgets.QApplication.translate("ClientEdit", "CEP:", None, -1))
        self.lbStreet.setText(QtWidgets.QApplication.translate("ClientEdit", "Logradouro:", None, -1))
        self.lbNumber.setText(QtWidgets.QApplication.translate("ClientEdit", "Nº:", None, -1))
        self.lbComp.setText(QtWidgets.QApplication.translate("ClientEdit", "Complemento:", None, -1))
        self.lbDistrict.setText(QtWidgets.QApplication.translate("ClientEdit", "Bairro:", None, -1))
        self.lbCity.setText(QtWidgets.QApplication.translate("ClientEdit", "Cidade:", None, -1))
        self.lbState.setText(QtWidgets.QApplication.translate("ClientEdit", "Estado:", None, -1))
        self.lbContry.setText(QtWidgets.QApplication.translate("ClientEdit", "País:", None, -1))
        self.pbSave.setText(QtWidgets.QApplication.translate("ClientEdit", "Salvar", None, -1))
        self.pbDelete.setText(QtWidgets.QApplication.translate("ClientEdit", "Excluir", None, -1))
        self.pbNew.setText(QtWidgets.QApplication.translate("ClientEdit", "Nova OS", None, -1))
        self.pbExit.setText(QtWidgets.QApplication.translate("ClientEdit", "Sair", None, -1))

